In [ ]:
# !pip install -q transformers sentence-transformers
!pip install -q torch-geometric
# !pip install -q spacy
# !python -m spacy download en_core_web_sm

In [ ]:
!pip install -q torch-geometric

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 27.1 MB/s eta 0:00:00

In [ ]:
import os
import spacy
import torch
import random
import numpy as np
import pandas as pd
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
from PIL import Image
from tqdm import tqdm

from transformers import (
    AutoTokenizer,
    AutoModel,
    AutoProcessor,
    CLIPVisionModel
)
from torch.cuda.amp import (
    autocast,
    GradScaler
)

from torch.utils.data import (
    Dataset,
    DataLoader
)

from torch_geometric.data import (
    Data,
    Batch
)

from torch_geometric.nn import (
    GATv2Conv,
    global_mean_pool
)

from sklearn.metrics import (
    accuracy_score,
    f1_score
)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import re

In [ ]:
class CFG:

    TRAIN_CSV="/content/train.csv"

    DEV_CSV="/content/dev.csv"

    GRAPH_CACHE="/content/graph_cache.pt"

    DEVICE="cuda" if torch.cuda.is_available() else "cpu"

    TEXT_MODEL="sentence-transformers/all-MiniLM-L6-v2"

    IMAGE_MODEL="openai/clip-vit-base-patch32"

    MAX_LEN=64

    BATCH_SIZE=8

    EPOCHS=5

    LR=2e-5

    GRAPH_DIM=128

    HIDDEN_DIM=384

    DROPOUT=0.2

In [ ]:
def seed_everything(seed=42):

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    torch.cuda.manual_seed_all(seed)

seed_everything()

In [ ]:
nlp=spacy.load("en_core_web_sm")

In [ ]:
tokenizer=AutoTokenizer.from_pretrained(
    CFG.TEXT_MODEL
)
image_processor=AutoProcessor.from_pretrained(
    CFG.IMAGE_MODEL
)
text_encoder=AutoModel.from_pretrained(
    CFG.TEXT_MODEL
).to(CFG.DEVICE)

image_encoder=CLIPVisionModel.from_pretrained(
    CFG.IMAGE_MODEL
).to(CFG.DEVICE)

for p in text_encoder.parameters():
    p.requires_grad=False

for p in image_encoder.parameters():
    p.requires_grad=False

text_encoder.eval()

image_encoder.eval()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

CLIPVisionModel LOAD REPORT from: openai/clip-vit-base-patch32
Key                                                          | Status     |  |
-------------------------------------------------------------+------------+--+-
text_model.encoder.layers.{0...11}.layer_norm2.weight        | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.layer_norm1.bias          | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.self_attn.out_proj.bias   | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.mlp.fc1.bias              | UNEXPECTED |  |
text_model.final_layer_norm.bias                             | UNEXPECTED |  |
text_model.final_layer_norm.weight                           | UNEXPECTED |  |
logit_scale                                                  | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.layer_norm2.bias          | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.mlp.fc2.weight            | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.self_attn.v_proj.weight   | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.self_attn.out_proj.weight | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.self_attn.k_proj.weight   | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.mlp.fc1.weight            | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.self_attn.v_proj.bias     | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.layer_norm1.weight        | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.self_attn.q_proj.bias     | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.self_attn.k_proj.bias     | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.self_attn.q_proj.weight   | UNEXPECTED |  |
text_model.embeddings.token_embedding.weight                 | UNEXPECTED |  |
text_model.encoder.layers.{0...11}.mlp.fc2.bias              | UNEXPECTED |  |
text_model.embeddings.position_embedding.weight              | UNEXPECTED |  |
text_model.embeddings.position_ids                           | UNEXPECTED |  |
text_projection.weight                                       | UNEXPECTED |  |
vision_model.embeddings.position_ids                         | UNEXPECTED |  |
visual_projection.weight                                     | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

CLIPVisionModel(
  (vision_model): CLIPVisionTransformer(
    (embeddings): CLIPVisionEmbeddings(
      (patch_embedding): Conv2d(3, 768, kernel_size=(32, 32), stride=(32, 32), bias=False)
      (position_embedding): Embedding(50, 768)
    )
    (pre_layrnorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (encoder): CLIPEncoder(
      (layers): ModuleList(
        (0-11): 12 x CLIPEncoderLayer(
          (self_attn): CLIPAttention(
            (k_proj): Linear(in_features=768, out_features=768, bias=True)
            (v_proj): Linear(in_features=768, out_features=768, bias=True)
            (q_proj): Linear(in_features=768, out_features=768, bias=True)
            (out_proj): Linear(in_features=768, out_features=768, bias=True)
          )
          (layer_norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (mlp): CLIPMLP(
            (activation_fn): QuickGELUActivation()
            (fc1): Linear(in_features=768, out_features=3072, bias=True)
            (fc2): Linear(in_features=3072, out_features=768, bias=True)
          )
          (layer_norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        )
      )
    )
    (post_layernorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
)

In [ ]:
@torch.no_grad()
def build_graph(text):

    doc=nlp(text)

    tokens=[]

    for token in doc:

        if token.is_stop:
            continue

        if not token.is_alpha:
            continue

        tokens.append(token.text.lower())

    if len(tokens)==0:
        tokens=["empty"]

    unique_tokens=list(dict.fromkeys(tokens))

    node_map={
        tok:i for i,tok in enumerate(unique_tokens)
    }

    encoded=tokenizer(
        unique_tokens,
        padding=True,
        truncation=True,
        max_length=8,
        return_tensors="pt"
    ).to(CFG.DEVICE)

    outputs=text_encoder(**encoded)

    node_features=outputs.last_hidden_state[:,0,:].cpu()

    edges=[]

    for token in doc:

        if token.text.lower() not in node_map:
            continue

        if token.head.text.lower() not in node_map:
            continue

        src=node_map[token.head.text.lower()]

        dst=node_map[token.text.lower()]

        edges.append([src,dst])

    if len(edges)==0:
        edges=[[0,0]]

    edge_index=torch.tensor(
        edges,
        dtype=torch.long
    ).t().contiguous()

    graph=Data(
        x=node_features,
        edge_index=edge_index
    )

    return graph

In [ ]:
def build_graph_cache(csv_path):

    df=pd.read_csv(csv_path)

    graphs=[]

    for text in tqdm(df["transcription"].astype(str).tolist()):

        graphs.append(build_graph(text))

    return graphs

if not os.path.exists(CFG.GRAPH_CACHE):

    train_graphs=build_graph_cache(
        CFG.TRAIN_CSV
    )

    dev_graphs=build_graph_cache(
        CFG.DEV_CSV
    )

    torch.save({
        "train":train_graphs,
        "dev":dev_graphs
    },CFG.GRAPH_CACHE)

graph_cache=torch.load(
    CFG.GRAPH_CACHE,
    weights_only=False
)

In [ ]:
class MemeDataset(Dataset):

    def __init__(self,csv_path,graphs):

        self.df=pd.read_csv(csv_path)

        self.graphs=graphs

    def __len__(self):

        return len(self.df)

    def __getitem__(self,idx):

        row=self.df.iloc[idx]

        image=Image.open(
            row["image_path"]
        ).convert("RGB")

        text=str(
            row["transcription"]
        )

        graph=self.graphs[idx]

        label=torch.tensor(
            row["label"],
            dtype=torch.float32
        )

        return {
            "image":image,
            "text":text,
            "graph":graph,
            "label":label
        }

In [ ]:
def collate_fn(batch):

    images=[
        x["image"] for x in batch
    ]

    texts=[
        x["text"] for x in batch
    ]

    graphs=Batch.from_data_list(
        [x["graph"] for x in batch]
    )

    labels=torch.stack([
        x["label"] for x in batch
    ])

    return {
        "images":images,
        "texts":texts,
        "graphs":graphs,
        "labels":labels
    }

In [ ]:

class GraphEncoder(nn.Module):

    def __init__(self):

        super().__init__()

        self.gat1=GATv2Conv(
            384,
            CFG.GRAPH_DIM,
            heads=2,
            dropout=CFG.DROPOUT
        )

        self.gat2=GATv2Conv(
            CFG.GRAPH_DIM*2,
            CFG.GRAPH_DIM,
            heads=1,
            concat=False,
            dropout=CFG.DROPOUT
        )

        self.proj=nn.Linear(
            CFG.GRAPH_DIM,
            384
        )

    def forward(self,graph):

        x=graph.x.to(CFG.DEVICE)

        edge_index=graph.edge_index.to(
            CFG.DEVICE
        )

        batch=graph.batch.to(
            CFG.DEVICE
        )

        x=self.gat1(
            x,
            edge_index
        )

        x=F.elu(x)

        x=self.gat2(
            x,
            edge_index
        )

        x=global_mean_pool(
            x,
            batch
        )

        x=self.proj(x)

        return x

In [ ]:
class Fusion(nn.Module):

    def __init__(self):

        super().__init__()

        self.attn=nn.MultiheadAttention(
            embed_dim=384,
            num_heads=4,
            batch_first=True
        )

        self.fc=nn.Sequential(

            nn.Linear(384*3,384),

            nn.LayerNorm(384),

            nn.GELU(),

            nn.Dropout(CFG.DROPOUT)
        )

    def forward(
        self,
        text_emb,
        image_emb,
        graph_emb
    ):

        print("TEXT:",text_emb.shape)
        print("IMAGE:",image_emb.shape)
        print("GRAPH:",graph_emb.shape)

        if image_emb.shape[-1]!=384:
            raise ValueError(
                f"Image dim wrong: {image_emb.shape}"
            )

        if text_emb.shape[-1]!=384:
            raise ValueError(
                f"Text dim wrong: {text_emb.shape}"
            )

        if graph_emb.shape[-1]!=384:
            raise ValueError(
                f"Graph dim wrong: {graph_emb.shape}"
            )

        text_emb=text_emb.unsqueeze(1)

        image_emb=image_emb.unsqueeze(1)

        attn_out,_=self.attn(
            text_emb,
            image_emb,
            image_emb
        )

        fused=torch.cat([
            attn_out.squeeze(1),
            image_emb.squeeze(1),
            graph_emb
        ],dim=1)

        fused=self.fc(fused)

        return fused

In [ ]:
class MemeModel(nn.Module):

    def __init__(self):

        super().__init__()

        self.graph_encoder=GraphEncoder()

        self.fusion=Fusion()

        self.image_proj=nn.Linear(
            768,
            384
        )

        self.classifier=nn.Sequential(

            nn.Linear(384,256),

            nn.LayerNorm(256),

            nn.GELU(),

            nn.Dropout(CFG.DROPOUT),

            nn.Linear(256,1)
        )

    @torch.no_grad()
    def encode_text(self,texts):

        encoded=tokenizer(
            texts,
            padding=True,
            truncation=True,
            max_length=CFG.MAX_LEN,
            return_tensors="pt"
        ).to(CFG.DEVICE)

        outputs=text_encoder(**encoded)

        emb=outputs.last_hidden_state[:,0,:]

        return emb

    @torch.no_grad()
    def encode_image(self,images):

        encoded=image_processor(
            images=images,
            return_tensors="pt"
        ).to(CFG.DEVICE)

        outputs=image_encoder(**encoded)

        emb=outputs.pooler_output

        emb=self.image_proj(emb)

        return emb

    def forward(self,batch):

        text_emb=self.encode_text(
            batch["texts"]
        )

        image_emb=self.encode_image(
            batch["images"]
        )

        graph_emb=self.graph_encoder(
            batch["graphs"]
        )

        fused=self.fusion(
            text_emb,
            image_emb,
            graph_emb
        )

        logits=self.classifier(
            fused
        )

        return logits.squeeze(1)

In [ ]:
train_dataset=MemeDataset(
    CFG.TRAIN_CSV,
    graph_cache["train"]
)

In [ ]:
dev_dataset=MemeDataset(
    CFG.DEV_CSV,
    graph_cache["dev"]
)

In [ ]:
train_loader=DataLoader(
    train_dataset,
    batch_size=CFG.BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_fn,
    pin_memory=True
)

dev_loader=DataLoader(
    dev_dataset,
    batch_size=CFG.BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_fn,
    pin_memory=True
)

In [ ]:
model=MemeModel().to(CFG.DEVICE)

In [ ]:
criterion=nn.BCEWithLogitsLoss()

optimizer=torch.optim.AdamW(
    model.parameters(),
    lr=CFG.LR
)

In [ ]:
for epoch in range(CFG.EPOCHS):

    model.train()

    train_losses=[]

    for batch in tqdm(train_loader):

        labels=batch["labels"].to(
            CFG.DEVICE
        )

        optimizer.zero_grad()

        with torch.amp.autocast("cuda"):

            logits=model(batch)

            loss=criterion(
                logits,
                labels
            )

        loss.backward()

        optimizer.step()

        train_losses.append(
            loss.item()
        )

    print(
        f"Epoch {epoch+1} Loss:",
        np.mean(train_losses)
    )

  0%|          | 1/1175 [00:03<1:12:29,  3.70s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 2/1175 [00:07<1:10:40,  3.62s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 3/1175 [00:10<1:11:43,  3.67s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 4/1175 [00:14<1:09:17,  3.55s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 5/1175 [00:19<1:18:38,  4.03s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 6/1175 [00:23<1:16:50,  3.94s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 7/1175 [00:26<1:15:34,  3.88s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 8/1175 [00:29<1:10:52,  3.64s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 9/1175 [00:33<1:09:27,  3.57s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 10/1175 [00:36<1:07:43,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 11/1175 [00:39<1:06:52,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 12/1175 [00:43<1:05:50,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 13/1175 [00:46<1:03:09,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 14/1175 [00:49<1:03:40,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|▏         | 15/1175 [00:52<1:03:49,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|▏         | 16/1175 [00:56<1:03:30,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|▏         | 17/1175 [01:00<1:07:11,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 18/1175 [01:03<1:04:59,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 19/1175 [01:06<1:03:54,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 20/1175 [01:09<1:05:32,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 21/1175 [01:13<1:03:41,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 22/1175 [01:16<1:02:29,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 23/1175 [01:20<1:05:56,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 24/1175 [01:24<1:09:04,  3.60s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 25/1175 [01:27<1:09:01,  3.60s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 26/1175 [01:31<1:08:22,  3.57s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 27/1175 [01:34<1:07:21,  3.52s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 28/1175 [01:37<1:06:04,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 29/1175 [01:41<1:06:49,  3.50s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 30/1175 [01:44<1:04:45,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 31/1175 [01:47<1:03:45,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 32/1175 [01:51<1:04:23,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 33/1175 [01:54<1:02:34,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 34/1175 [01:57<1:04:00,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 35/1175 [02:01<1:03:27,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 36/1175 [02:04<1:01:50,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 37/1175 [02:08<1:05:34,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 38/1175 [02:11<1:06:35,  3.51s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 39/1175 [02:15<1:04:52,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 40/1175 [02:18<1:04:59,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 41/1175 [02:21<1:04:16,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▎         | 42/1175 [02:26<1:09:22,  3.67s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▎         | 43/1175 [02:29<1:06:45,  3.54s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▎         | 44/1175 [02:33<1:07:56,  3.60s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 45/1175 [02:36<1:08:37,  3.64s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 46/1175 [02:40<1:07:56,  3.61s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 47/1175 [02:44<1:10:10,  3.73s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 48/1175 [02:48<1:11:04,  3.78s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 49/1175 [02:51<1:09:27,  3.70s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 50/1175 [02:55<1:09:42,  3.72s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 51/1175 [02:58<1:04:01,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 52/1175 [03:02<1:06:12,  3.54s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 53/1175 [03:05<1:04:02,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 54/1175 [03:08<1:00:19,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 55/1175 [03:11<1:02:55,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 56/1175 [03:15<1:03:27,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 57/1175 [03:18<1:02:30,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 58/1175 [03:21<1:02:13,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 59/1175 [03:25<1:02:02,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 60/1175 [03:28<1:02:53,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 61/1175 [03:32<1:04:30,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 62/1175 [03:35<1:04:13,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 63/1175 [03:39<1:04:50,  3.50s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 64/1175 [03:43<1:07:03,  3.62s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 65/1175 [03:46<1:07:19,  3.64s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 66/1175 [03:50<1:05:09,  3.53s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 67/1175 [03:53<1:03:34,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 68/1175 [03:56<1:02:00,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 69/1175 [04:00<1:02:21,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 70/1175 [04:03<1:02:03,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 71/1175 [04:06<1:00:38,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 72/1175 [04:10<1:02:59,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 73/1175 [04:13<1:03:06,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▋         | 74/1175 [04:16<1:02:07,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▋         | 75/1175 [04:19<58:25,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▋         | 76/1175 [04:22<58:19,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 77/1175 [04:26<58:30,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 78/1175 [04:29<1:01:13,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 79/1175 [04:32<1:00:22,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 80/1175 [04:36<1:01:10,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 81/1175 [04:39<59:30,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 82/1175 [04:42<1:00:08,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 83/1175 [04:45<59:04,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 84/1175 [04:49<59:34,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 85/1175 [04:52<57:40,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 86/1175 [04:55<58:19,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 87/1175 [04:58<58:44,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 88/1175 [05:02<58:14,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 89/1175 [05:05<57:55,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 90/1175 [05:08<58:53,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 91/1175 [05:13<1:07:15,  3.72s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 92/1175 [05:16<1:05:20,  3.62s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 93/1175 [05:20<1:03:49,  3.54s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 94/1175 [05:23<1:04:20,  3.57s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 95/1175 [05:27<1:02:52,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 96/1175 [05:30<1:04:36,  3.59s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 97/1175 [05:34<1:02:32,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 98/1175 [05:37<1:00:13,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 99/1175 [05:40<1:00:03,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▊         | 100/1175 [05:44<1:02:20,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▊         | 101/1175 [05:47<1:00:47,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▊         | 102/1175 [05:51<1:01:36,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 103/1175 [05:54<1:01:12,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 104/1175 [05:57<1:01:03,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 105/1175 [06:00<58:48,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 106/1175 [06:04<59:07,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 107/1175 [06:07<59:17,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 108/1175 [06:11<59:51,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 109/1175 [06:14<58:14,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 110/1175 [06:17<57:42,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 111/1175 [06:20<59:56,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 112/1175 [06:24<59:39,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 113/1175 [06:27<1:00:31,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 114/1175 [06:31<59:03,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 115/1175 [06:34<59:01,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 116/1175 [06:37<57:33,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 117/1175 [06:40<58:16,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 118/1175 [06:44<58:08,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 119/1175 [06:47<58:24,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 120/1175 [06:50<58:00,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 121/1175 [06:53<56:46,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 122/1175 [06:57<58:05,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 123/1175 [07:00<58:38,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 124/1175 [07:03<57:13,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 125/1175 [07:07<57:52,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 126/1175 [07:10<57:02,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 127/1175 [07:13<57:37,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 128/1175 [07:16<56:31,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 129/1175 [07:19<55:44,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 130/1175 [07:23<57:04,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 131/1175 [07:26<58:28,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 132/1175 [07:30<58:26,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█▏        | 133/1175 [07:33<56:40,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█▏        | 134/1175 [07:37<59:37,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█▏        | 135/1175 [07:40<59:22,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 136/1175 [07:43<57:44,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 137/1175 [07:46<56:02,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 138/1175 [07:50<56:54,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 139/1175 [07:53<58:41,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 140/1175 [07:57<58:31,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 141/1175 [08:00<58:32,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 142/1175 [08:04<58:36,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 143/1175 [08:07<59:36,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 144/1175 [08:10<57:47,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 145/1175 [08:13<55:48,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 146/1175 [08:17<58:59,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 147/1175 [08:20<56:51,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 148/1175 [08:23<56:00,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 149/1175 [08:27<55:30,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 150/1175 [08:30<55:36,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 151/1175 [08:34<58:59,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 152/1175 [08:37<57:47,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 153/1175 [08:40<57:37,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 154/1175 [08:43<55:42,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 155/1175 [08:46<54:40,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 156/1175 [08:50<54:21,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 157/1175 [08:53<54:58,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 158/1175 [08:56<54:57,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▎        | 159/1175 [08:59<54:52,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▎        | 160/1175 [09:03<54:47,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▎        | 161/1175 [09:06<56:21,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 162/1175 [09:10<56:51,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 163/1175 [09:13<57:50,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 164/1175 [09:17<57:38,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 165/1175 [09:20<57:35,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 166/1175 [09:23<56:13,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 167/1175 [09:26<54:13,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 168/1175 [09:29<53:06,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 169/1175 [09:32<52:54,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 170/1175 [09:35<51:12,  3.06s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 171/1175 [09:38<52:06,  3.11s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 172/1175 [09:42<53:28,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 173/1175 [09:45<52:39,  3.15s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 174/1175 [09:48<54:21,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 175/1175 [09:52<53:54,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 176/1175 [09:55<55:05,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 177/1175 [09:58<53:35,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 178/1175 [10:01<53:03,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 179/1175 [10:04<53:08,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 180/1175 [10:08<54:56,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 181/1175 [10:11<54:35,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 182/1175 [10:14<54:21,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 183/1175 [10:18<53:16,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 184/1175 [10:21<52:09,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 185/1175 [10:24<53:26,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 186/1175 [10:27<52:56,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 187/1175 [10:31<54:02,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 188/1175 [10:34<55:28,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 189/1175 [10:38<56:06,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 190/1175 [10:41<55:19,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▋        | 191/1175 [10:44<54:38,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▋        | 192/1175 [10:48<55:02,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▋        | 193/1175 [10:51<55:01,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 194/1175 [10:55<57:37,  3.52s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 195/1175 [10:58<56:38,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 196/1175 [11:02<55:58,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 197/1175 [11:05<54:39,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 198/1175 [11:08<54:12,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 199/1175 [11:12<56:07,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 200/1175 [11:15<55:13,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 201/1175 [11:18<54:20,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 202/1175 [11:22<54:36,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 203/1175 [11:24<50:20,  3.11s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 204/1175 [11:28<51:37,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 205/1175 [11:31<52:10,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 206/1175 [11:34<52:37,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 207/1175 [11:37<51:49,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 208/1175 [11:40<50:23,  3.13s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 209/1175 [11:44<52:00,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 210/1175 [11:47<53:07,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 211/1175 [11:51<53:18,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 212/1175 [11:54<54:35,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 213/1175 [11:58<55:20,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 214/1175 [12:01<54:40,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 215/1175 [12:05<56:55,  3.56s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 216/1175 [12:08<54:31,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 217/1175 [12:11<55:02,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▊        | 218/1175 [12:15<54:07,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▊        | 219/1175 [12:18<54:47,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▊        | 220/1175 [12:22<54:22,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 221/1175 [12:25<54:39,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 222/1175 [12:28<53:54,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 223/1175 [12:32<53:37,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 224/1175 [12:35<54:15,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 225/1175 [12:39<53:09,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 226/1175 [12:42<51:35,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 227/1175 [12:45<52:33,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 228/1175 [12:48<51:59,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 229/1175 [12:51<51:03,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 230/1175 [12:54<50:19,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 231/1175 [12:58<49:49,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 232/1175 [13:01<52:01,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 233/1175 [13:04<51:04,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 234/1175 [13:08<51:30,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 235/1175 [13:11<51:38,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 236/1175 [13:14<51:35,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 237/1175 [13:18<51:07,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 238/1175 [13:21<50:53,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 239/1175 [13:24<50:14,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 240/1175 [13:27<49:16,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 241/1175 [13:30<49:57,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 242/1175 [13:33<50:00,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 243/1175 [13:36<49:07,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 244/1175 [13:40<48:56,  3.15s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 245/1175 [13:43<50:01,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 246/1175 [13:46<50:44,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 247/1175 [13:50<50:36,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 248/1175 [13:53<49:55,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 249/1175 [13:56<50:28,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██▏       | 250/1175 [13:59<49:29,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██▏       | 251/1175 [14:02<48:51,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██▏       | 252/1175 [14:05<47:57,  3.12s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 253/1175 [14:09<49:44,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 254/1175 [14:12<48:44,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 255/1175 [14:16<52:11,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 256/1175 [14:19<52:54,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 257/1175 [14:23<52:48,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 258/1175 [14:26<52:20,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 259/1175 [14:30<52:00,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 260/1175 [14:33<52:04,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 261/1175 [14:36<51:53,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 262/1175 [14:40<51:23,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 263/1175 [14:43<51:35,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 264/1175 [14:47<53:36,  3.53s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 265/1175 [14:50<51:38,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 266/1175 [14:53<50:55,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 267/1175 [14:56<49:46,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 268/1175 [15:00<49:28,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 269/1175 [15:03<50:45,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 270/1175 [15:06<49:47,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 271/1175 [15:10<49:54,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 272/1175 [15:13<51:10,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 273/1175 [15:17<51:34,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 274/1175 [15:20<51:11,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 275/1175 [15:23<50:28,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 276/1175 [15:27<49:12,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▎       | 277/1175 [15:29<47:15,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▎       | 278/1175 [15:33<47:44,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▎       | 279/1175 [15:36<48:34,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 280/1175 [15:40<53:11,  3.57s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 281/1175 [15:44<51:42,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 282/1175 [15:47<50:46,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 283/1175 [15:50<49:05,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 284/1175 [15:53<49:28,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 285/1175 [15:56<47:00,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 286/1175 [15:59<46:59,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 287/1175 [16:03<48:08,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 288/1175 [16:06<46:44,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 289/1175 [16:09<46:52,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 290/1175 [16:12<47:52,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 291/1175 [16:16<47:30,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 292/1175 [16:19<49:05,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 293/1175 [16:23<49:24,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 294/1175 [16:26<49:19,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 295/1175 [16:29<49:33,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 296/1175 [16:33<49:29,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 297/1175 [16:36<47:49,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 298/1175 [16:39<49:46,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 299/1175 [16:43<49:36,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 300/1175 [16:46<48:45,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 301/1175 [16:49<47:58,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 302/1175 [16:53<49:07,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 303/1175 [16:56<48:36,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 304/1175 [17:00<49:39,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 305/1175 [17:03<49:56,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 306/1175 [17:07<52:23,  3.62s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 307/1175 [17:11<52:05,  3.60s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 308/1175 [17:14<49:58,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▋       | 309/1175 [17:17<49:04,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▋       | 310/1175 [17:20<48:02,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▋       | 311/1175 [17:23<46:32,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 312/1175 [17:26<46:03,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 313/1175 [17:30<46:15,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 314/1175 [17:33<46:01,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 315/1175 [17:36<47:13,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 316/1175 [17:40<47:41,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 317/1175 [17:43<47:12,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 318/1175 [17:47<48:10,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 319/1175 [17:50<48:19,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 320/1175 [17:54<49:11,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 321/1175 [17:57<48:05,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 322/1175 [18:00<49:21,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 323/1175 [18:04<48:12,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 324/1175 [18:07<48:44,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 325/1175 [18:10<47:27,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 326/1175 [18:14<46:30,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 327/1175 [18:19<54:05,  3.83s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 328/1175 [18:22<51:34,  3.65s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 329/1175 [18:25<49:59,  3.55s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 330/1175 [18:29<50:03,  3.55s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 331/1175 [18:31<46:38,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 332/1175 [18:34<44:59,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 333/1175 [18:38<45:55,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 334/1175 [18:41<45:23,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▊       | 335/1175 [18:44<45:34,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▊       | 336/1175 [18:47<44:09,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▊       | 337/1175 [18:51<45:20,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 338/1175 [18:54<44:36,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 339/1175 [18:57<44:15,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 340/1175 [19:00<45:35,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 341/1175 [19:03<43:48,  3.15s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 342/1175 [19:07<44:17,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 343/1175 [19:10<45:41,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 344/1175 [19:13<44:43,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 345/1175 [19:16<44:50,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 346/1175 [19:20<44:34,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 347/1175 [19:23<44:03,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 348/1175 [19:26<43:24,  3.15s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 349/1175 [19:29<42:32,  3.09s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 350/1175 [19:32<41:56,  3.05s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 351/1175 [19:35<43:27,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 352/1175 [19:38<43:39,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 353/1175 [19:42<43:35,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 354/1175 [19:45<43:29,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 355/1175 [19:48<43:07,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 356/1175 [19:51<42:28,  3.11s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 357/1175 [19:54<43:41,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 358/1175 [19:58<44:27,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 359/1175 [20:01<44:10,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 360/1175 [20:04<44:52,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 361/1175 [20:08<45:20,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 362/1175 [20:11<45:52,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 363/1175 [20:14<45:27,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 364/1175 [20:18<45:00,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 365/1175 [20:21<45:15,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 366/1175 [20:25<45:41,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 367/1175 [20:28<43:56,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███▏      | 368/1175 [20:31<44:43,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███▏      | 369/1175 [20:34<43:56,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███▏      | 370/1175 [20:38<45:21,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 371/1175 [20:41<44:37,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 372/1175 [20:44<43:25,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 373/1175 [20:48<46:32,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 374/1175 [20:51<45:19,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 375/1175 [20:54<44:07,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 376/1175 [20:58<43:13,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 377/1175 [21:01<43:56,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 378/1175 [21:04<42:58,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 379/1175 [21:07<43:03,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 380/1175 [21:11<44:12,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 381/1175 [21:14<43:50,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 382/1175 [21:17<43:01,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 383/1175 [21:20<42:51,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 384/1175 [21:24<43:18,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 385/1175 [21:27<43:58,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 386/1175 [21:31<45:18,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 387/1175 [21:34<44:46,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 388/1175 [21:38<44:02,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 389/1175 [21:41<44:09,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 390/1175 [21:44<43:01,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 391/1175 [21:47<43:07,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 392/1175 [21:52<46:46,  3.58s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 393/1175 [21:55<45:02,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▎      | 394/1175 [21:58<44:21,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▎      | 395/1175 [22:01<43:16,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▎      | 396/1175 [22:05<45:58,  3.54s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 397/1175 [22:09<46:04,  3.55s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 398/1175 [22:12<44:18,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 399/1175 [22:15<42:48,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 400/1175 [22:18<42:51,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 401/1175 [22:22<43:33,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 402/1175 [22:25<43:37,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 403/1175 [22:28<41:56,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 404/1175 [22:31<41:28,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 405/1175 [22:35<42:24,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 406/1175 [22:38<42:51,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 407/1175 [22:42<43:02,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 408/1175 [22:45<42:22,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 409/1175 [22:48<41:19,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 410/1175 [22:51<41:14,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 411/1175 [22:55<42:28,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 412/1175 [22:58<42:14,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 413/1175 [23:01<42:24,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 414/1175 [23:05<43:57,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 415/1175 [23:09<43:38,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 416/1175 [23:12<43:11,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 417/1175 [23:16<46:02,  3.64s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 418/1175 [23:20<45:23,  3.60s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 419/1175 [23:23<43:17,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 420/1175 [23:27<46:16,  3.68s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 421/1175 [23:30<44:44,  3.56s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 422/1175 [23:33<43:31,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 423/1175 [23:36<41:21,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 424/1175 [23:40<41:38,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 425/1175 [23:43<41:48,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▋      | 426/1175 [23:46<41:20,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▋      | 427/1175 [23:49<40:05,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▋      | 428/1175 [23:52<39:34,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 429/1175 [23:56<39:08,  3.15s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 430/1175 [23:59<40:22,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 431/1175 [24:03<41:07,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 432/1175 [24:06<41:30,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 433/1175 [24:09<41:01,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 434/1175 [24:12<40:17,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 435/1175 [24:15<39:17,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 436/1175 [24:19<40:12,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 437/1175 [24:22<40:33,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 438/1175 [24:25<39:26,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 439/1175 [24:28<39:48,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 440/1175 [24:32<40:42,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 441/1175 [24:35<39:47,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 442/1175 [24:38<37:55,  3.10s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 443/1175 [24:41<38:42,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 444/1175 [24:44<37:54,  3.11s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 445/1175 [24:47<38:23,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 446/1175 [24:51<38:43,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 447/1175 [24:54<38:11,  3.15s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 448/1175 [24:57<38:56,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 449/1175 [25:01<39:54,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 450/1175 [25:04<39:17,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 451/1175 [25:07<39:00,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 452/1175 [25:10<40:12,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▊      | 453/1175 [25:14<39:37,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▊      | 454/1175 [25:17<39:14,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▊      | 455/1175 [25:20<37:42,  3.14s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 456/1175 [25:23<37:27,  3.13s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 457/1175 [25:26<38:46,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 458/1175 [25:30<39:10,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 459/1175 [25:33<39:20,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 460/1175 [25:37<40:59,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 461/1175 [25:40<40:07,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 462/1175 [25:43<39:50,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 463/1175 [25:47<39:24,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 464/1175 [25:50<38:14,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|███▉      | 465/1175 [25:53<37:21,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|███▉      | 466/1175 [25:56<37:44,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|███▉      | 467/1175 [25:59<38:27,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|███▉      | 468/1175 [26:02<38:04,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|███▉      | 469/1175 [26:06<37:52,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 470/1175 [26:09<37:41,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 471/1175 [26:12<37:56,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 472/1175 [26:15<37:27,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 473/1175 [26:18<37:08,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 474/1175 [26:22<37:17,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 475/1175 [26:25<37:22,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 476/1175 [26:28<36:31,  3.13s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 477/1175 [26:31<37:16,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 478/1175 [26:34<36:41,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 479/1175 [26:38<37:17,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 480/1175 [26:41<37:22,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 481/1175 [26:44<36:25,  3.15s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 482/1175 [26:47<36:28,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 483/1175 [26:50<36:36,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 484/1175 [26:54<38:24,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████▏     | 485/1175 [26:57<37:43,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████▏     | 486/1175 [27:00<37:42,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████▏     | 487/1175 [27:04<37:59,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 488/1175 [27:07<39:04,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 489/1175 [27:10<37:38,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 490/1175 [27:14<39:53,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 491/1175 [27:18<38:57,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 492/1175 [27:21<38:08,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 493/1175 [27:24<36:38,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 494/1175 [27:27<36:15,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 495/1175 [27:30<36:07,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 496/1175 [27:33<35:47,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 497/1175 [27:36<36:38,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 498/1175 [27:40<37:20,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 499/1175 [27:43<37:21,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 500/1175 [27:47<37:30,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 501/1175 [27:50<37:28,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 502/1175 [27:53<36:47,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 503/1175 [27:56<36:22,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 504/1175 [28:00<36:49,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 505/1175 [28:03<35:56,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 506/1175 [28:09<45:17,  4.06s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 507/1175 [28:12<42:47,  3.84s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 508/1175 [28:15<40:13,  3.62s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 509/1175 [28:19<39:49,  3.59s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 510/1175 [28:22<38:45,  3.50s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 511/1175 [28:25<37:31,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▎     | 512/1175 [28:29<38:30,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▎     | 513/1175 [28:32<38:22,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▎     | 514/1175 [28:38<44:01,  4.00s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 515/1175 [28:41<42:18,  3.85s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 516/1175 [28:44<39:46,  3.62s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 517/1175 [28:48<39:53,  3.64s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 518/1175 [28:51<38:36,  3.53s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 519/1175 [28:54<37:51,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 520/1175 [28:58<37:51,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 521/1175 [29:01<37:15,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 522/1175 [29:04<36:21,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 523/1175 [29:08<36:53,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 524/1175 [29:11<36:34,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 525/1175 [29:14<36:18,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 526/1175 [29:18<36:08,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 527/1175 [29:21<36:09,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 528/1175 [29:24<35:10,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 529/1175 [29:27<34:52,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 530/1175 [29:31<34:36,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 531/1175 [29:34<35:02,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 532/1175 [29:37<34:57,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 533/1175 [29:40<34:57,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 534/1175 [29:44<35:32,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 535/1175 [29:47<34:39,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 536/1175 [29:50<34:39,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 537/1175 [29:53<33:19,  3.13s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 538/1175 [29:57<34:59,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 539/1175 [30:00<33:55,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 540/1175 [30:03<35:19,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 541/1175 [30:06<33:57,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 542/1175 [30:10<36:01,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 543/1175 [30:14<35:48,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▋     | 544/1175 [30:17<35:04,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▋     | 545/1175 [30:20<34:19,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▋     | 546/1175 [30:23<34:48,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 547/1175 [30:27<35:24,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 548/1175 [30:30<35:05,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 549/1175 [30:34<34:56,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 550/1175 [30:37<34:39,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 551/1175 [30:40<34:43,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 552/1175 [30:43<34:34,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 553/1175 [30:47<34:49,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 554/1175 [30:50<35:15,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 555/1175 [30:54<34:31,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 556/1175 [30:57<34:34,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 557/1175 [31:00<33:46,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 558/1175 [31:04<34:07,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 559/1175 [31:07<33:35,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 560/1175 [31:10<32:23,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 561/1175 [31:13<32:44,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 562/1175 [31:17<35:31,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 563/1175 [31:21<36:03,  3.53s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 564/1175 [31:24<34:27,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 565/1175 [31:27<34:46,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 566/1175 [31:30<33:10,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 567/1175 [31:33<32:28,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 568/1175 [31:36<32:41,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 569/1175 [31:40<32:10,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▊     | 570/1175 [31:43<33:46,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▊     | 571/1175 [31:46<33:21,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▊     | 572/1175 [31:50<33:39,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 573/1175 [31:53<33:38,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 574/1175 [31:57<33:11,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 575/1175 [32:00<32:50,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 576/1175 [32:03<33:05,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 577/1175 [32:07<33:33,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 578/1175 [32:10<32:59,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 579/1175 [32:13<32:53,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 580/1175 [32:17<33:20,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 581/1175 [32:20<34:44,  3.51s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 582/1175 [32:24<35:47,  3.62s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 583/1175 [32:28<36:00,  3.65s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 584/1175 [32:31<34:10,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 585/1175 [32:34<32:22,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 586/1175 [32:37<32:19,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 587/1175 [32:41<32:09,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 588/1175 [32:44<32:37,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 589/1175 [32:47<32:33,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 590/1175 [32:50<31:46,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 591/1175 [32:54<32:45,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 592/1175 [32:58<33:10,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 593/1175 [33:02<35:17,  3.64s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 594/1175 [33:05<33:25,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 595/1175 [33:08<33:14,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 596/1175 [33:11<32:11,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 597/1175 [33:14<31:15,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 598/1175 [33:17<30:35,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 599/1175 [33:20<30:17,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 600/1175 [33:24<30:19,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 601/1175 [33:27<30:50,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 602/1175 [33:30<31:02,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████▏    | 603/1175 [33:33<29:25,  3.09s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████▏    | 604/1175 [33:36<30:07,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████▏    | 605/1175 [33:39<30:11,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 606/1175 [33:43<30:15,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 607/1175 [33:46<30:38,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 608/1175 [33:49<30:22,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 609/1175 [33:52<30:07,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 610/1175 [33:56<30:01,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 611/1175 [33:59<30:05,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 612/1175 [34:02<31:07,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 613/1175 [34:06<31:47,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 614/1175 [34:09<31:12,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 615/1175 [34:13<31:16,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 616/1175 [34:16<30:57,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 617/1175 [34:19<29:43,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 618/1175 [34:22<29:22,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 619/1175 [34:25<29:48,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 620/1175 [34:28<28:45,  3.11s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 621/1175 [34:31<28:38,  3.10s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 622/1175 [34:34<29:15,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 623/1175 [34:38<29:54,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 624/1175 [34:41<29:51,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 625/1175 [34:44<30:02,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 626/1175 [34:48<29:43,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 627/1175 [34:51<29:32,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 628/1175 [34:55<30:58,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▎    | 629/1175 [34:58<30:26,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▎    | 630/1175 [35:01<31:16,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▎    | 631/1175 [35:05<30:50,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 632/1175 [35:08<31:17,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 633/1175 [35:12<31:53,  3.53s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 634/1175 [35:15<31:01,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 635/1175 [35:18<29:35,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 636/1175 [35:21<29:25,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 637/1175 [35:25<30:02,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 638/1175 [35:28<30:05,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 639/1175 [35:32<29:44,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 640/1175 [35:35<29:40,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 641/1175 [35:38<29:30,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 642/1175 [35:41<28:42,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 643/1175 [35:44<28:10,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 644/1175 [35:48<28:32,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 645/1175 [35:51<28:39,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 646/1175 [35:54<28:21,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 647/1175 [35:58<29:39,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 648/1175 [36:01<29:41,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 649/1175 [36:04<29:13,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 650/1175 [36:08<29:50,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 651/1175 [36:12<30:18,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 652/1175 [36:15<29:32,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 653/1175 [36:19<30:13,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 654/1175 [36:22<28:53,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 655/1175 [36:25<28:04,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 656/1175 [36:28<28:15,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 657/1175 [36:31<27:33,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 658/1175 [36:34<26:40,  3.10s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 659/1175 [36:37<26:51,  3.12s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 660/1175 [36:41<28:03,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▋    | 661/1175 [36:44<27:45,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▋    | 662/1175 [36:47<27:23,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▋    | 663/1175 [36:50<27:07,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 664/1175 [36:53<27:51,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 665/1175 [36:57<27:32,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 666/1175 [37:00<28:26,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 667/1175 [37:03<27:47,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 668/1175 [37:06<27:01,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 669/1175 [37:10<27:00,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 670/1175 [37:13<26:48,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 671/1175 [37:16<26:39,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 672/1175 [37:19<26:02,  3.11s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 673/1175 [37:22<27:07,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 674/1175 [37:26<26:47,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 675/1175 [37:29<27:04,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 676/1175 [37:32<26:55,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 677/1175 [37:35<26:51,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 678/1175 [37:38<26:29,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 679/1175 [37:42<27:18,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 680/1175 [37:45<27:09,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 681/1175 [37:49<27:17,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 682/1175 [37:52<27:13,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 683/1175 [37:55<27:05,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 684/1175 [37:59<27:29,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 685/1175 [38:02<27:43,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 686/1175 [38:06<27:44,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 687/1175 [38:09<27:26,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▊    | 688/1175 [38:12<26:59,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▊    | 689/1175 [38:15<27:05,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▊    | 690/1175 [38:19<26:49,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 691/1175 [38:22<26:29,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 692/1175 [38:25<26:46,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 693/1175 [38:29<26:58,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 694/1175 [38:32<26:36,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 695/1175 [38:35<26:51,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 696/1175 [38:39<26:16,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 697/1175 [38:42<26:42,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 698/1175 [38:46<26:54,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 699/1175 [38:49<28:05,  3.54s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 700/1175 [38:53<27:12,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 701/1175 [38:57<28:33,  3.61s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 702/1175 [39:00<27:48,  3.53s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 703/1175 [39:03<26:09,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 704/1175 [39:06<25:20,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 705/1175 [39:09<25:15,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 706/1175 [39:12<25:05,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 707/1175 [39:15<24:43,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 708/1175 [39:19<24:43,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 709/1175 [39:22<24:57,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 710/1175 [39:25<24:51,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 711/1175 [39:29<26:05,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 712/1175 [39:32<25:13,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 713/1175 [39:36<26:40,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 714/1175 [39:39<26:18,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 715/1175 [39:42<25:47,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 716/1175 [39:46<25:41,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 717/1175 [39:49<24:47,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 718/1175 [39:52<24:45,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 719/1175 [39:56<25:37,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████▏   | 720/1175 [39:59<25:04,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████▏   | 721/1175 [40:02<25:29,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████▏   | 722/1175 [40:05<24:53,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 723/1175 [40:09<26:03,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 724/1175 [40:12<24:59,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 725/1175 [40:16<25:08,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 726/1175 [40:19<24:25,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 727/1175 [40:22<24:19,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 728/1175 [40:26<25:25,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 729/1175 [40:29<25:07,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 730/1175 [40:33<25:33,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 731/1175 [40:35<23:49,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 732/1175 [40:39<23:56,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 733/1175 [40:42<25:04,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 734/1175 [40:45<23:46,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 735/1175 [40:48<23:20,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 736/1175 [40:52<23:38,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 737/1175 [40:55<23:30,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 738/1175 [40:58<23:35,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 739/1175 [41:02<24:10,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 740/1175 [41:05<24:24,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 741/1175 [41:08<23:32,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 742/1175 [41:11<23:16,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 743/1175 [41:14<23:01,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 744/1175 [41:17<22:18,  3.11s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 745/1175 [41:21<22:49,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 746/1175 [41:24<22:52,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▎   | 747/1175 [41:27<22:44,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▎   | 748/1175 [41:30<22:48,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▎   | 749/1175 [41:34<23:48,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 750/1175 [41:37<23:52,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 751/1175 [41:41<23:38,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 752/1175 [41:44<23:57,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 753/1175 [41:48<23:54,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 754/1175 [41:51<23:05,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 755/1175 [41:54<23:06,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 756/1175 [41:57<23:13,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 757/1175 [42:01<23:46,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 758/1175 [42:04<23:45,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 759/1175 [42:08<23:10,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 760/1175 [42:11<23:09,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 761/1175 [42:14<22:35,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 762/1175 [42:18<23:15,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 763/1175 [42:21<22:43,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 764/1175 [42:25<24:45,  3.61s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 765/1175 [42:28<23:25,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 766/1175 [42:31<23:18,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 767/1175 [42:35<23:34,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 768/1175 [42:38<23:16,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 769/1175 [42:42<22:32,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 770/1175 [42:45<22:06,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 771/1175 [42:48<22:15,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 772/1175 [42:51<22:13,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 773/1175 [42:55<22:06,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 774/1175 [42:58<21:48,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 775/1175 [43:01<21:26,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 776/1175 [43:04<21:24,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 777/1175 [43:08<22:24,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 778/1175 [43:11<22:30,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▋   | 779/1175 [43:15<22:13,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▋   | 780/1175 [43:18<21:42,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▋   | 781/1175 [43:21<21:32,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 782/1175 [43:24<21:13,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 783/1175 [43:27<21:03,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 784/1175 [43:31<21:13,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 785/1175 [43:34<20:44,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 786/1175 [43:37<20:47,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 787/1175 [43:40<21:14,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 788/1175 [43:44<21:13,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 789/1175 [43:47<22:01,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 790/1175 [43:50<21:11,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 791/1175 [43:54<21:05,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 792/1175 [43:57<21:00,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 793/1175 [44:00<20:55,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 794/1175 [44:03<20:32,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 795/1175 [44:07<20:28,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 796/1175 [44:10<20:14,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 797/1175 [44:13<20:18,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 798/1175 [44:16<20:28,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 799/1175 [44:20<21:11,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 800/1175 [44:24<21:18,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 801/1175 [44:27<21:23,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 802/1175 [44:30<20:37,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 803/1175 [44:33<20:30,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 804/1175 [44:37<20:24,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▊   | 805/1175 [44:40<19:48,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▊   | 806/1175 [44:43<19:44,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▊   | 807/1175 [44:46<19:42,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 808/1175 [44:49<19:37,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 809/1175 [44:52<19:26,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 810/1175 [44:56<19:49,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 811/1175 [44:59<19:14,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 812/1175 [45:02<19:06,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 813/1175 [45:05<19:34,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 814/1175 [45:08<19:15,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 815/1175 [45:12<19:47,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 816/1175 [45:16<20:30,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 817/1175 [45:19<19:52,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 818/1175 [45:22<19:52,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 819/1175 [45:25<19:20,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 820/1175 [45:29<19:55,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 821/1175 [45:32<19:44,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 822/1175 [45:36<20:06,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 823/1175 [45:39<19:59,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 824/1175 [45:42<19:40,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 825/1175 [45:46<19:28,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 826/1175 [45:49<19:08,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 827/1175 [45:52<19:07,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 828/1175 [45:57<20:54,  3.61s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 829/1175 [46:00<20:27,  3.55s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 830/1175 [46:03<19:31,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 831/1175 [46:06<18:51,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 832/1175 [46:09<18:26,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 833/1175 [46:12<18:09,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 834/1175 [46:16<18:59,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 835/1175 [46:19<18:48,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 836/1175 [46:22<18:44,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 837/1175 [46:26<18:21,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████▏  | 838/1175 [46:29<18:21,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████▏  | 839/1175 [46:32<18:37,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████▏  | 840/1175 [46:36<18:49,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 841/1175 [46:39<18:36,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 842/1175 [46:42<18:01,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 843/1175 [46:46<18:12,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 844/1175 [46:49<17:55,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 845/1175 [46:52<17:46,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 846/1175 [46:55<17:54,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 847/1175 [46:59<18:07,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 848/1175 [47:02<18:23,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 849/1175 [47:05<18:13,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 850/1175 [47:09<18:28,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 851/1175 [47:12<18:19,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 852/1175 [47:15<17:49,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 853/1175 [47:19<17:56,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 854/1175 [47:22<17:46,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 855/1175 [47:25<17:11,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 856/1175 [47:28<16:48,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 857/1175 [47:31<16:34,  3.13s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 858/1175 [47:35<17:07,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 859/1175 [47:38<17:02,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 860/1175 [47:41<17:02,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 861/1175 [47:45<17:10,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 862/1175 [47:48<17:20,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 863/1175 [47:51<17:18,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▎  | 864/1175 [47:55<17:32,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▎  | 865/1175 [47:58<17:10,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▎  | 866/1175 [48:01<17:09,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 867/1175 [48:05<17:02,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 868/1175 [48:08<17:42,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 869/1175 [48:11<16:52,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 870/1175 [48:15<16:34,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 871/1175 [48:18<16:03,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 872/1175 [48:20<15:21,  3.04s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 873/1175 [48:24<15:40,  3.12s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 874/1175 [48:27<15:37,  3.11s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 875/1175 [48:30<15:24,  3.08s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 876/1175 [48:33<15:50,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 877/1175 [48:36<15:03,  3.03s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 878/1175 [48:39<15:19,  3.10s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 879/1175 [48:43<16:17,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 880/1175 [48:46<16:18,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 881/1175 [48:50<16:37,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 882/1175 [48:53<16:05,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 883/1175 [48:56<16:21,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 884/1175 [48:59<16:01,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 885/1175 [49:03<15:57,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 886/1175 [49:06<16:19,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 887/1175 [49:10<16:30,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 888/1175 [49:13<16:01,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 889/1175 [49:17<16:15,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 890/1175 [49:20<16:31,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 891/1175 [49:24<16:23,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 892/1175 [49:27<16:02,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 893/1175 [49:30<15:35,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 894/1175 [49:34<16:01,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 895/1175 [49:37<15:55,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▋  | 896/1175 [49:41<16:07,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▋  | 897/1175 [49:44<15:26,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▋  | 898/1175 [49:47<15:49,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 899/1175 [49:52<17:37,  3.83s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 900/1175 [49:55<15:36,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 901/1175 [49:58<15:15,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 902/1175 [50:01<15:28,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 903/1175 [50:05<15:46,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 904/1175 [50:08<15:14,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 905/1175 [50:11<14:58,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 906/1175 [50:15<15:15,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 907/1175 [50:18<15:26,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 908/1175 [50:22<15:22,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 909/1175 [50:25<15:12,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 910/1175 [50:28<14:47,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 911/1175 [50:31<14:13,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 912/1175 [50:35<14:28,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 913/1175 [50:38<14:20,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 914/1175 [50:41<14:17,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 915/1175 [50:46<15:38,  3.61s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 916/1175 [50:50<16:00,  3.71s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 917/1175 [50:53<15:16,  3.55s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 918/1175 [50:56<14:33,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 919/1175 [50:59<13:43,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 920/1175 [51:02<14:08,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 921/1175 [51:06<14:12,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 922/1175 [51:09<14:08,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▊  | 923/1175 [51:12<13:51,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▊  | 924/1175 [51:15<13:40,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▊  | 925/1175 [51:19<13:46,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 926/1175 [51:23<14:16,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 927/1175 [51:26<14:15,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 928/1175 [51:30<14:09,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 929/1175 [51:33<13:52,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 930/1175 [51:36<13:21,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 931/1175 [51:39<13:10,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 932/1175 [51:43<13:35,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 933/1175 [51:46<13:39,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 934/1175 [51:49<13:38,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 935/1175 [51:53<13:22,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 936/1175 [51:56<13:20,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 937/1175 [51:59<13:15,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 938/1175 [52:03<13:05,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 939/1175 [52:06<12:59,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 940/1175 [52:10<13:20,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 941/1175 [52:13<13:36,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 942/1175 [52:17<13:49,  3.56s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 943/1175 [52:20<12:56,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 944/1175 [52:23<12:42,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 945/1175 [52:27<13:04,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 946/1175 [52:30<12:49,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 947/1175 [52:33<12:38,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 948/1175 [52:37<12:59,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 949/1175 [52:40<13:07,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 950/1175 [52:44<12:41,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 951/1175 [52:47<12:25,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 952/1175 [52:50<12:32,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 953/1175 [52:54<12:50,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 954/1175 [52:57<12:22,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████▏ | 955/1175 [53:00<11:58,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████▏ | 956/1175 [53:03<11:47,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████▏ | 957/1175 [53:07<11:55,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 958/1175 [53:10<11:52,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 959/1175 [53:13<11:53,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 960/1175 [53:16<11:40,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 961/1175 [53:20<11:38,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 962/1175 [53:23<11:58,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 963/1175 [53:27<11:49,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 964/1175 [53:30<11:40,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 965/1175 [53:33<11:39,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 966/1175 [53:37<11:48,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 967/1175 [53:40<11:56,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 968/1175 [53:44<11:38,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 969/1175 [53:47<11:33,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 970/1175 [53:50<11:25,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 971/1175 [53:54<11:24,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 972/1175 [53:57<11:32,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 973/1175 [54:00<11:14,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 974/1175 [54:04<11:05,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 975/1175 [54:07<10:56,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 976/1175 [54:10<10:37,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 977/1175 [54:13<10:50,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 978/1175 [54:17<10:49,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 979/1175 [54:20<10:37,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 980/1175 [54:23<10:37,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 981/1175 [54:27<10:53,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▎ | 982/1175 [54:30<10:39,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▎ | 983/1175 [54:33<10:31,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▎ | 984/1175 [54:36<10:10,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 985/1175 [54:40<10:32,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 986/1175 [54:43<10:18,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 987/1175 [54:46<10:00,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 988/1175 [54:49<10:02,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 989/1175 [54:52<09:34,  3.09s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 990/1175 [54:55<09:36,  3.11s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 991/1175 [54:58<09:46,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 992/1175 [55:02<09:38,  3.16s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 993/1175 [55:05<09:44,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 994/1175 [55:08<09:30,  3.15s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 995/1175 [55:11<09:22,  3.12s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 996/1175 [55:14<09:28,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 997/1175 [55:18<09:43,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 998/1175 [55:21<09:39,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 999/1175 [55:24<09:46,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1000/1175 [55:28<09:44,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1001/1175 [55:31<09:56,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1002/1175 [55:34<09:27,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1003/1175 [55:38<09:43,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1004/1175 [55:42<09:45,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1005/1175 [55:45<09:33,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1006/1175 [55:48<09:34,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1007/1175 [55:51<09:11,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1008/1175 [55:55<09:07,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1009/1175 [55:58<09:03,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1010/1175 [56:01<08:47,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1011/1175 [56:04<08:51,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1012/1175 [56:08<08:56,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1013/1175 [56:11<08:37,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▋ | 1014/1175 [56:14<08:41,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▋ | 1015/1175 [56:17<08:45,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▋ | 1016/1175 [56:21<08:48,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1017/1175 [56:24<08:40,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1018/1175 [56:27<08:22,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1019/1175 [56:30<08:29,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1020/1175 [56:34<08:32,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1021/1175 [56:37<08:45,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1022/1175 [56:41<08:41,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1023/1175 [56:44<08:39,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1024/1175 [56:47<08:25,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1025/1175 [56:52<09:03,  3.62s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1026/1175 [56:55<08:42,  3.51s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1027/1175 [56:58<08:39,  3.51s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1028/1175 [57:02<08:20,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1029/1175 [57:05<08:08,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1030/1175 [57:08<08:01,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1031/1175 [57:11<07:57,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1032/1175 [57:14<07:43,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1033/1175 [57:18<07:44,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1034/1175 [57:21<07:53,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1035/1175 [57:25<07:52,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1036/1175 [57:28<07:41,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1037/1175 [57:31<07:27,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1038/1175 [57:35<07:42,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1039/1175 [57:38<07:31,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▊ | 1040/1175 [57:41<07:24,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▊ | 1041/1175 [57:44<07:08,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▊ | 1042/1175 [57:47<07:12,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1043/1175 [57:51<07:25,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1044/1175 [57:54<07:16,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1045/1175 [57:58<07:19,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1046/1175 [58:01<07:12,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1047/1175 [58:04<06:41,  3.14s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1048/1175 [58:07<06:43,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1049/1175 [58:11<07:03,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1050/1175 [58:15<07:14,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1051/1175 [58:18<07:10,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1052/1175 [58:21<07:02,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1053/1175 [58:24<06:43,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1054/1175 [58:28<06:47,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1055/1175 [58:31<06:35,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1056/1175 [58:34<06:35,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1057/1175 [58:37<06:20,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1058/1175 [58:41<06:42,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1059/1175 [58:44<06:23,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1060/1175 [58:48<06:37,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1061/1175 [58:52<06:29,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1062/1175 [58:55<06:29,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1063/1175 [58:58<06:22,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1064/1175 [59:02<06:33,  3.54s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1065/1175 [59:06<06:29,  3.54s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1066/1175 [59:09<06:17,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1067/1175 [59:12<06:00,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1068/1175 [59:15<05:49,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1069/1175 [59:19<05:52,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1070/1175 [59:21<05:30,  3.15s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1071/1175 [59:25<05:38,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1072/1175 [59:28<05:42,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████▏| 1073/1175 [59:32<05:45,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████▏| 1074/1175 [59:35<05:43,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████▏| 1075/1175 [59:39<05:41,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1076/1175 [59:42<05:40,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1077/1175 [59:45<05:30,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1078/1175 [59:49<05:17,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1079/1175 [59:52<05:21,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1080/1175 [59:56<05:23,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1081/1175 [59:59<05:28,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1082/1175 [1:00:03<05:25,  3.50s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1083/1175 [1:00:06<05:19,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1084/1175 [1:00:10<05:15,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1085/1175 [1:00:13<05:03,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1086/1175 [1:00:16<04:55,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1087/1175 [1:00:20<04:56,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1088/1175 [1:00:23<04:54,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1089/1175 [1:00:26<04:54,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1090/1175 [1:00:30<04:57,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1091/1175 [1:00:34<04:51,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1092/1175 [1:00:37<04:37,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1093/1175 [1:00:40<04:41,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1094/1175 [1:00:44<04:34,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1095/1175 [1:00:47<04:24,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1096/1175 [1:00:50<04:14,  3.23s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1097/1175 [1:00:53<04:15,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1098/1175 [1:00:57<04:19,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▎| 1099/1175 [1:01:00<04:10,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▎| 1100/1175 [1:01:03<04:06,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▎| 1101/1175 [1:01:06<04:02,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1102/1175 [1:01:10<04:16,  3.51s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1103/1175 [1:01:14<04:09,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1104/1175 [1:01:17<04:09,  3.52s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1105/1175 [1:01:21<04:03,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1106/1175 [1:01:25<04:25,  3.85s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1107/1175 [1:01:29<04:11,  3.69s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1108/1175 [1:01:32<03:51,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1109/1175 [1:01:36<03:55,  3.57s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1110/1175 [1:01:39<03:55,  3.63s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1111/1175 [1:01:43<03:50,  3.61s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1112/1175 [1:01:46<03:37,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1113/1175 [1:01:49<03:30,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1114/1175 [1:01:53<03:28,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1115/1175 [1:01:56<03:23,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1116/1175 [1:01:59<03:21,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1117/1175 [1:02:03<03:18,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1118/1175 [1:02:06<03:15,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1119/1175 [1:02:10<03:12,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1120/1175 [1:02:13<02:58,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1121/1175 [1:02:16<02:59,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1122/1175 [1:02:19<02:54,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1123/1175 [1:02:22<02:48,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1124/1175 [1:02:26<02:48,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1125/1175 [1:02:29<02:45,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1126/1175 [1:02:32<02:40,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1127/1175 [1:02:36<02:37,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1128/1175 [1:02:39<02:37,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1129/1175 [1:02:43<02:35,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1130/1175 [1:02:46<02:27,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▋| 1131/1175 [1:02:49<02:21,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▋| 1132/1175 [1:02:52<02:20,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▋| 1133/1175 [1:02:56<02:24,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1134/1175 [1:02:59<02:18,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1135/1175 [1:03:03<02:15,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1136/1175 [1:03:06<02:13,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1137/1175 [1:03:10<02:12,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1138/1175 [1:03:13<02:04,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1139/1175 [1:03:16<02:03,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1140/1175 [1:03:20<02:04,  3.55s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1141/1175 [1:03:25<02:08,  3.79s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1142/1175 [1:03:28<01:58,  3.60s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1143/1175 [1:03:31<01:50,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1144/1175 [1:03:35<01:49,  3.52s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1145/1175 [1:03:38<01:41,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1146/1175 [1:03:41<01:38,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1147/1175 [1:03:45<01:36,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1148/1175 [1:03:48<01:32,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1149/1175 [1:03:52<01:29,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1150/1175 [1:03:54<01:22,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1151/1175 [1:03:57<01:16,  3.18s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1152/1175 [1:04:01<01:15,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1153/1175 [1:04:05<01:14,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1154/1175 [1:04:08<01:10,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1155/1175 [1:04:11<01:06,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1156/1175 [1:04:14<01:02,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1157/1175 [1:04:17<00:57,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▊| 1158/1175 [1:04:20<00:53,  3.14s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▊| 1159/1175 [1:04:23<00:50,  3.17s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▊| 1160/1175 [1:04:27<00:47,  3.14s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1161/1175 [1:04:30<00:44,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1162/1175 [1:04:33<00:41,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1163/1175 [1:04:36<00:36,  3.04s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1164/1175 [1:04:39<00:32,  2.99s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1165/1175 [1:04:42<00:32,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1166/1175 [1:04:46<00:28,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1167/1175 [1:04:49<00:26,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1168/1175 [1:04:52<00:22,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1169/1175 [1:04:56<00:19,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1170/1175 [1:04:59<00:16,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1171/1175 [1:05:03<00:13,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1172/1175 [1:05:06<00:09,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1173/1175 [1:05:09<00:06,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1174/1175 [1:05:12<00:03,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|██████████| 1175/1175 [1:05:14<00:00,  3.33s/it]

TEXT: torch.Size([3, 384])
IMAGE: torch.Size([3, 384])
GRAPH: torch.Size([3, 384])
Epoch 1 Loss: 0.5087876273723358

  0%|          | 1/1175 [00:00<03:07,  6.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 2/1175 [00:00<03:10,  6.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 3/1175 [00:00<03:09,  6.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 4/1175 [00:00<03:00,  6.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 6/1175 [00:01<03:25,  5.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 7/1175 [00:01<03:27,  5.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 8/1175 [00:01<03:27,  5.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 10/1175 [00:01<03:32,  5.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 11/1175 [00:01<03:25,  5.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 13/1175 [00:02<03:27,  5.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|▏         | 15/1175 [00:02<03:24,  5.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|▏         | 17/1175 [00:02<03:28,  5.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 19/1175 [00:03<03:26,  5.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 21/1175 [00:03<03:27,  5.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 22/1175 [00:03<03:31,  5.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 25/1175 [00:04<03:36,  5.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 27/1175 [00:04<03:34,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 29/1175 [00:05<03:09,  6.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 31/1175 [00:05<02:58,  6.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 33/1175 [00:05<02:48,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 35/1175 [00:05<02:36,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 37/1175 [00:06<02:35,  7.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 39/1175 [00:06<02:40,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 41/1175 [00:06<02:42,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▎         | 43/1175 [00:07<02:39,  7.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 45/1175 [00:07<02:32,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 47/1175 [00:07<02:32,  7.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 49/1175 [00:07<02:35,  7.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 51/1175 [00:08<02:36,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 53/1175 [00:08<02:37,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 55/1175 [00:08<02:37,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 57/1175 [00:09<02:38,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 59/1175 [00:09<02:37,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 61/1175 [00:09<02:31,  7.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 63/1175 [00:09<02:35,  7.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 65/1175 [00:10<02:28,  7.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 67/1175 [00:10<02:34,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 69/1175 [00:10<02:30,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 71/1175 [00:10<02:27,  7.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 73/1175 [00:11<02:26,  7.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▋         | 75/1175 [00:11<02:28,  7.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 77/1175 [00:11<02:29,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 79/1175 [00:12<02:28,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 81/1175 [00:12<02:26,  7.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 83/1175 [00:12<02:22,  7.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 85/1175 [00:12<02:18,  7.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 87/1175 [00:13<02:24,  7.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 89/1175 [00:13<02:28,  7.32it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 91/1175 [00:13<02:27,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 93/1175 [00:13<02:26,  7.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 95/1175 [00:14<02:29,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 97/1175 [00:14<02:27,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 99/1175 [00:14<02:24,  7.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▊         | 101/1175 [00:15<02:42,  6.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 103/1175 [00:15<02:48,  6.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 105/1175 [00:15<03:03,  5.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 107/1175 [00:16<03:01,  5.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 109/1175 [00:16<03:01,  5.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 111/1175 [00:16<03:07,  5.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 112/1175 [00:17<03:11,  5.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 114/1175 [00:17<03:24,  5.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 116/1175 [00:17<03:14,  5.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 118/1175 [00:18<03:04,  5.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 119/1175 [00:18<03:12,  5.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 122/1175 [00:18<03:15,  5.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 123/1175 [00:19<03:30,  4.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 126/1175 [00:19<02:53,  6.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 128/1175 [00:19<02:33,  6.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 130/1175 [00:20<02:27,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 132/1175 [00:20<02:34,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█▏        | 134/1175 [00:20<02:23,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 136/1175 [00:20<02:19,  7.43it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 138/1175 [00:21<02:15,  7.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 140/1175 [00:21<02:18,  7.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 142/1175 [00:21<02:24,  7.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 144/1175 [00:22<02:20,  7.32it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 146/1175 [00:22<02:14,  7.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 148/1175 [00:22<02:17,  7.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 150/1175 [00:22<02:20,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 152/1175 [00:23<02:19,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 154/1175 [00:23<02:18,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 156/1175 [00:23<02:13,  7.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 158/1175 [00:23<02:15,  7.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▎        | 160/1175 [00:24<02:19,  7.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 162/1175 [00:24<02:20,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 164/1175 [00:24<02:16,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 166/1175 [00:25<02:13,  7.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 168/1175 [00:25<02:09,  7.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 170/1175 [00:25<02:19,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 172/1175 [00:25<02:15,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 174/1175 [00:26<02:13,  7.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 176/1175 [00:26<02:11,  7.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 178/1175 [00:26<02:18,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 180/1175 [00:26<02:15,  7.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 182/1175 [00:27<02:16,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 184/1175 [00:27<02:12,  7.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 186/1175 [00:27<02:13,  7.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 188/1175 [00:28<02:15,  7.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 190/1175 [00:28<02:14,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▋        | 192/1175 [00:28<02:12,  7.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 194/1175 [00:28<02:15,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 196/1175 [00:29<02:18,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 198/1175 [00:29<02:26,  6.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 199/1175 [00:29<02:44,  5.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 202/1175 [00:30<02:58,  5.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 203/1175 [00:30<03:00,  5.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 206/1175 [00:31<03:06,  5.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 208/1175 [00:31<03:00,  5.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 210/1175 [00:31<02:58,  5.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 212/1175 [00:32<02:51,  5.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 214/1175 [00:32<02:49,  5.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 215/1175 [00:32<02:59,  5.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▊        | 218/1175 [00:33<02:53,  5.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▊        | 220/1175 [00:33<02:54,  5.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 222/1175 [00:33<02:39,  5.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 224/1175 [00:34<02:25,  6.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 226/1175 [00:34<02:11,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 228/1175 [00:34<02:26,  6.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 230/1175 [00:35<02:21,  6.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 232/1175 [00:35<02:10,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 234/1175 [00:35<02:10,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 236/1175 [00:35<02:05,  7.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 238/1175 [00:36<02:05,  7.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 240/1175 [00:36<02:08,  7.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 242/1175 [00:36<02:09,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 244/1175 [00:36<02:03,  7.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 246/1175 [00:37<02:06,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 248/1175 [00:37<02:03,  7.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██▏       | 250/1175 [00:37<02:01,  7.58it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██▏       | 252/1175 [00:38<02:09,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 254/1175 [00:38<02:05,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 256/1175 [00:38<02:04,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 258/1175 [00:38<02:02,  7.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 260/1175 [00:39<02:04,  7.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 262/1175 [00:39<02:04,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 264/1175 [00:39<02:03,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 266/1175 [00:39<02:05,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 268/1175 [00:40<02:07,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 270/1175 [00:40<02:11,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 272/1175 [00:40<02:01,  7.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 274/1175 [00:41<01:57,  7.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 276/1175 [00:41<02:01,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▎       | 278/1175 [00:41<02:02,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 280/1175 [00:41<02:04,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 282/1175 [00:42<02:03,  7.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 284/1175 [00:42<02:01,  7.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 286/1175 [00:42<01:58,  7.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 288/1175 [00:42<01:55,  7.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 290/1175 [00:43<02:01,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 292/1175 [00:43<02:00,  7.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 294/1175 [00:43<02:04,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 296/1175 [00:44<02:20,  6.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 297/1175 [00:44<02:31,  5.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 300/1175 [00:44<02:33,  5.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 302/1175 [00:45<02:30,  5.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 304/1175 [00:45<02:32,  5.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 306/1175 [00:45<02:26,  5.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 308/1175 [00:46<02:35,  5.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▋       | 310/1175 [00:46<02:37,  5.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 312/1175 [00:47<02:33,  5.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 314/1175 [00:47<02:33,  5.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 315/1175 [00:47<02:33,  5.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 317/1175 [00:48<02:43,  5.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 319/1175 [00:48<02:22,  6.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 321/1175 [00:48<02:06,  6.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 323/1175 [00:48<02:06,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 325/1175 [00:49<02:06,  6.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 327/1175 [00:49<01:56,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 329/1175 [00:49<01:57,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 331/1175 [00:49<01:54,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 333/1175 [00:50<01:52,  7.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▊       | 335/1175 [00:50<01:53,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▊       | 337/1175 [00:50<01:54,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 339/1175 [00:51<01:53,  7.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 341/1175 [00:51<01:53,  7.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 343/1175 [00:51<01:56,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 345/1175 [00:51<01:57,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 347/1175 [00:52<01:52,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 349/1175 [00:52<01:48,  7.58it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 351/1175 [00:52<01:49,  7.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 353/1175 [00:52<01:53,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 355/1175 [00:53<01:52,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 357/1175 [00:53<01:51,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 359/1175 [00:53<01:49,  7.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 361/1175 [00:54<01:52,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 363/1175 [00:54<01:49,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 365/1175 [00:54<01:49,  7.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 367/1175 [00:54<01:46,  7.58it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███▏      | 369/1175 [00:55<01:53,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 371/1175 [00:55<01:52,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 373/1175 [00:55<01:49,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 375/1175 [00:56<01:53,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 377/1175 [00:56<01:48,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 379/1175 [00:56<01:48,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 381/1175 [00:56<01:46,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 383/1175 [00:57<01:49,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 385/1175 [00:57<01:45,  7.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 387/1175 [00:57<01:45,  7.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 389/1175 [00:57<01:47,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 391/1175 [00:58<01:56,  6.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 393/1175 [00:58<02:10,  6.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▎      | 395/1175 [00:58<02:14,  5.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 397/1175 [00:59<02:20,  5.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 399/1175 [00:59<02:19,  5.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 401/1175 [01:00<02:17,  5.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 403/1175 [01:00<02:22,  5.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 405/1175 [01:00<02:13,  5.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 407/1175 [01:01<02:17,  5.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 409/1175 [01:01<02:18,  5.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 410/1175 [01:01<02:21,  5.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 413/1175 [01:02<02:18,  5.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 414/1175 [01:02<02:18,  5.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 416/1175 [01:02<02:13,  5.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 418/1175 [01:03<01:55,  6.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 420/1175 [01:03<01:45,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 422/1175 [01:03<01:45,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 424/1175 [01:03<01:45,  7.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▋      | 426/1175 [01:04<01:42,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▋      | 428/1175 [01:04<01:39,  7.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 430/1175 [01:04<01:43,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 432/1175 [01:04<01:43,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 434/1175 [01:05<01:39,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 436/1175 [01:05<01:39,  7.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 438/1175 [01:05<01:42,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 440/1175 [01:06<01:39,  7.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 442/1175 [01:06<01:39,  7.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 444/1175 [01:06<01:37,  7.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 446/1175 [01:06<01:35,  7.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 448/1175 [01:07<01:37,  7.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 450/1175 [01:07<01:40,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 452/1175 [01:07<01:38,  7.32it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▊      | 454/1175 [01:07<01:38,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 456/1175 [01:08<01:36,  7.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 458/1175 [01:08<01:39,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 460/1175 [01:08<01:35,  7.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 462/1175 [01:09<01:34,  7.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 464/1175 [01:09<01:31,  7.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|███▉      | 466/1175 [01:09<01:30,  7.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|███▉      | 468/1175 [01:09<01:36,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 470/1175 [01:10<01:34,  7.43it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 472/1175 [01:10<01:31,  7.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 474/1175 [01:10<01:33,  7.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 476/1175 [01:10<01:39,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 478/1175 [01:11<01:36,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 480/1175 [01:11<01:36,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 482/1175 [01:11<01:32,  7.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 484/1175 [01:12<01:38,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████▏     | 486/1175 [01:12<01:34,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 488/1175 [01:12<01:32,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 489/1175 [01:12<01:44,  6.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 491/1175 [01:13<01:57,  5.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 494/1175 [01:13<02:04,  5.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 496/1175 [01:14<02:03,  5.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 498/1175 [01:14<02:03,  5.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 500/1175 [01:14<01:58,  5.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 501/1175 [01:15<02:06,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 504/1175 [01:15<02:03,  5.43it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 505/1175 [01:15<02:03,  5.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 508/1175 [01:16<02:07,  5.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 510/1175 [01:16<02:03,  5.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▎     | 512/1175 [01:17<01:56,  5.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▎     | 514/1175 [01:17<01:41,  6.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 516/1175 [01:17<01:34,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 518/1175 [01:17<01:35,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 520/1175 [01:18<01:33,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 522/1175 [01:18<01:29,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 524/1175 [01:18<01:26,  7.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 526/1175 [01:19<01:27,  7.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 528/1175 [01:19<01:27,  7.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 530/1175 [01:19<01:28,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 532/1175 [01:19<01:29,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 534/1175 [01:20<01:27,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 536/1175 [01:20<01:28,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 538/1175 [01:20<01:26,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 540/1175 [01:20<01:26,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 542/1175 [01:21<01:25,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▋     | 544/1175 [01:21<01:26,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▋     | 546/1175 [01:21<01:25,  7.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 548/1175 [01:22<01:24,  7.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 550/1175 [01:22<01:24,  7.43it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 552/1175 [01:22<01:26,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 554/1175 [01:22<01:25,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 556/1175 [01:23<01:23,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 558/1175 [01:23<01:24,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 560/1175 [01:23<01:25,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 562/1175 [01:23<01:25,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 564/1175 [01:24<01:23,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 566/1175 [01:24<01:26,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 568/1175 [01:24<01:23,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▊     | 570/1175 [01:25<01:24,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▊     | 572/1175 [01:25<01:24,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 574/1175 [01:25<01:22,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 576/1175 [01:25<01:21,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 578/1175 [01:26<01:22,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 580/1175 [01:26<01:20,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 582/1175 [01:26<01:21,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 584/1175 [01:27<01:19,  7.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 585/1175 [01:27<01:29,  6.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 588/1175 [01:27<01:40,  5.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 590/1175 [01:28<01:37,  5.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 592/1175 [01:28<01:41,  5.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 593/1175 [01:28<01:48,  5.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 596/1175 [01:29<01:49,  5.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 598/1175 [01:29<01:46,  5.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 600/1175 [01:29<01:46,  5.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 601/1175 [01:30<01:45,  5.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 602/1175 [01:30<01:51,  5.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████▏    | 604/1175 [01:30<01:48,  5.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 606/1175 [01:31<01:48,  5.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 608/1175 [01:31<01:46,  5.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 610/1175 [01:31<01:39,  5.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 612/1175 [01:32<01:28,  6.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 614/1175 [01:32<01:20,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 616/1175 [01:32<01:18,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 618/1175 [01:32<01:17,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 619/1175 [01:33<01:18,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 621/1175 [01:33<02:21,  3.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 623/1175 [01:34<01:46,  5.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 625/1175 [01:34<01:28,  6.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 627/1175 [01:34<01:20,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▎    | 629/1175 [01:35<01:19,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▎    | 631/1175 [01:35<01:14,  7.32it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 633/1175 [01:35<01:13,  7.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 635/1175 [01:35<01:10,  7.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 637/1175 [01:36<01:14,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 639/1175 [01:36<01:12,  7.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 641/1175 [01:36<01:13,  7.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 643/1175 [01:36<01:12,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 645/1175 [01:37<01:12,  7.32it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 647/1175 [01:37<01:11,  7.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 649/1175 [01:37<01:10,  7.43it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 651/1175 [01:37<01:11,  7.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 653/1175 [01:38<01:13,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 655/1175 [01:38<01:11,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 657/1175 [01:38<01:10,  7.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 659/1175 [01:39<01:10,  7.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▋    | 661/1175 [01:39<01:08,  7.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▋    | 663/1175 [01:39<01:11,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 665/1175 [01:39<01:10,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 667/1175 [01:40<01:09,  7.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 669/1175 [01:40<01:08,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 671/1175 [01:40<01:09,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 673/1175 [01:41<01:09,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 675/1175 [01:41<01:08,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 677/1175 [01:41<01:13,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 679/1175 [01:41<01:22,  6.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 681/1175 [01:42<01:28,  5.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 683/1175 [01:42<01:26,  5.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 685/1175 [01:43<01:24,  5.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 686/1175 [01:43<01:27,  5.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▊    | 688/1175 [01:43<01:28,  5.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▊    | 690/1175 [01:44<01:29,  5.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 692/1175 [01:44<01:28,  5.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 694/1175 [01:44<01:27,  5.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 695/1175 [01:44<01:28,  5.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 698/1175 [01:45<01:30,  5.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 700/1175 [01:45<01:30,  5.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 702/1175 [01:46<01:17,  6.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 704/1175 [01:46<01:11,  6.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 706/1175 [01:46<01:06,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 708/1175 [01:46<01:03,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 710/1175 [01:47<01:03,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 712/1175 [01:47<01:02,  7.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 714/1175 [01:47<01:03,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 716/1175 [01:48<01:01,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 718/1175 [01:48<01:01,  7.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████▏   | 720/1175 [01:48<01:02,  7.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████▏   | 722/1175 [01:48<01:03,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 724/1175 [01:49<01:00,  7.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 726/1175 [01:49<00:59,  7.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 728/1175 [01:49<01:00,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 730/1175 [01:50<01:03,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 732/1175 [01:50<01:01,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 734/1175 [01:50<01:03,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 736/1175 [01:50<01:01,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 738/1175 [01:51<01:01,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 740/1175 [01:51<00:59,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 742/1175 [01:51<01:00,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 744/1175 [01:51<01:00,  7.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 746/1175 [01:52<00:57,  7.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▎   | 748/1175 [01:52<01:00,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 750/1175 [01:52<00:58,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 752/1175 [01:53<00:57,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 754/1175 [01:53<00:57,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 756/1175 [01:53<00:57,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 758/1175 [01:53<00:57,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 760/1175 [01:54<00:56,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 762/1175 [01:54<00:55,  7.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 764/1175 [01:54<01:00,  6.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 766/1175 [01:55<00:56,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 768/1175 [01:55<00:54,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 770/1175 [01:55<00:55,  7.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 772/1175 [01:55<00:57,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 774/1175 [01:56<01:06,  6.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 776/1175 [01:56<01:11,  5.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 778/1175 [01:57<01:12,  5.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▋   | 780/1175 [01:57<01:13,  5.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 782/1175 [01:57<01:12,  5.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 784/1175 [01:58<01:10,  5.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 786/1175 [01:58<01:07,  5.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 788/1175 [01:58<01:08,  5.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 790/1175 [01:59<01:11,  5.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 792/1175 [01:59<01:11,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 793/1175 [01:59<01:13,  5.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 796/1175 [02:00<01:10,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 798/1175 [02:00<01:03,  5.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 800/1175 [02:00<00:58,  6.43it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 802/1175 [02:01<00:55,  6.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 804/1175 [02:01<00:51,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▊   | 806/1175 [02:01<00:51,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 808/1175 [02:02<00:51,  7.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 810/1175 [02:02<00:51,  7.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 812/1175 [02:02<00:49,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 814/1175 [02:02<00:51,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 816/1175 [02:03<00:50,  7.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 818/1175 [02:03<00:50,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 820/1175 [02:03<00:48,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 822/1175 [02:04<00:46,  7.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 824/1175 [02:04<00:48,  7.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 826/1175 [02:04<00:48,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 828/1175 [02:04<00:47,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 830/1175 [02:05<00:46,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 832/1175 [02:05<00:47,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 834/1175 [02:05<00:46,  7.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 836/1175 [02:05<00:46,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████▏  | 838/1175 [02:06<00:47,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████▏  | 840/1175 [02:06<00:46,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 842/1175 [02:06<00:47,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 844/1175 [02:07<00:46,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 846/1175 [02:07<00:46,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 848/1175 [02:07<00:46,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 850/1175 [02:07<00:44,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 852/1175 [02:08<00:44,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 854/1175 [02:08<00:45,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 856/1175 [02:08<00:44,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 858/1175 [02:09<00:43,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 860/1175 [02:09<00:44,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 862/1175 [02:09<00:44,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▎  | 864/1175 [02:09<00:43,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▎  | 866/1175 [02:10<00:43,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 867/1175 [02:10<00:47,  6.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 870/1175 [02:10<00:52,  5.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 872/1175 [02:11<00:53,  5.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 873/1175 [02:11<00:54,  5.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 876/1175 [02:12<00:54,  5.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 877/1175 [02:12<00:55,  5.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 880/1175 [02:12<00:57,  5.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 881/1175 [02:13<00:54,  5.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 884/1175 [02:13<00:55,  5.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 886/1175 [02:14<00:55,  5.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 888/1175 [02:14<00:54,  5.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 889/1175 [02:14<00:54,  5.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 891/1175 [02:14<00:50,  5.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 893/1175 [02:15<00:43,  6.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 895/1175 [02:15<00:40,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▋  | 897/1175 [02:15<00:40,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 899/1175 [02:16<00:40,  6.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 901/1175 [02:16<00:38,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 903/1175 [02:16<00:38,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 905/1175 [02:16<00:38,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 907/1175 [02:17<00:36,  7.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 909/1175 [02:17<00:38,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 911/1175 [02:17<00:36,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 913/1175 [02:18<00:38,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 915/1175 [02:18<00:36,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 917/1175 [02:18<00:36,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 919/1175 [02:18<00:37,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 921/1175 [02:19<00:36,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▊  | 923/1175 [02:19<00:35,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▊  | 925/1175 [02:19<00:36,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 927/1175 [02:20<00:36,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 929/1175 [02:20<00:35,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 931/1175 [02:20<00:34,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 933/1175 [02:20<00:35,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 935/1175 [02:21<00:34,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 937/1175 [02:21<00:33,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 939/1175 [02:21<00:32,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 941/1175 [02:22<00:33,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 943/1175 [02:22<00:33,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 945/1175 [02:22<00:32,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 947/1175 [02:22<00:31,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 949/1175 [02:23<00:32,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 951/1175 [02:23<00:33,  6.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 953/1175 [02:23<00:31,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████▏ | 955/1175 [02:24<00:31,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████▏ | 957/1175 [02:24<00:30,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 959/1175 [02:24<00:31,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 961/1175 [02:24<00:33,  6.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 962/1175 [02:25<00:37,  5.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 963/1175 [02:25<00:39,  5.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 964/1175 [02:25<00:40,  5.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 966/1175 [02:26<00:40,  5.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 968/1175 [02:26<00:40,  5.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 970/1175 [02:26<00:40,  5.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 972/1175 [02:27<00:38,  5.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 974/1175 [02:27<00:38,  5.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 976/1175 [02:27<00:38,  5.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 977/1175 [02:28<00:38,  5.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 979/1175 [02:28<00:37,  5.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 981/1175 [02:28<00:37,  5.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▎ | 983/1175 [02:29<00:37,  5.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 986/1175 [02:29<00:30,  6.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 988/1175 [02:30<00:27,  6.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 990/1175 [02:30<00:25,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 992/1175 [02:30<00:27,  6.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 994/1175 [02:30<00:26,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 996/1175 [02:31<00:26,  6.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 998/1175 [02:31<00:25,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1000/1175 [02:31<00:24,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1002/1175 [02:32<00:24,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1004/1175 [02:32<00:24,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1006/1175 [02:32<00:23,  7.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1008/1175 [02:32<00:23,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1010/1175 [02:33<00:24,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1012/1175 [02:33<00:23,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▋ | 1014/1175 [02:33<00:23,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▋ | 1016/1175 [02:34<00:22,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1018/1175 [02:34<00:23,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1020/1175 [02:34<00:22,  6.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1022/1175 [02:34<00:22,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1024/1175 [02:35<00:21,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1026/1175 [02:35<00:22,  6.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1028/1175 [02:35<00:21,  6.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1030/1175 [02:36<00:21,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1032/1175 [02:36<00:20,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1034/1175 [02:36<00:20,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1036/1175 [02:37<00:20,  6.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1038/1175 [02:37<00:19,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▊ | 1040/1175 [02:37<00:19,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▊ | 1042/1175 [02:37<00:19,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1044/1175 [02:38<00:19,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1046/1175 [02:38<00:18,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1048/1175 [02:38<00:18,  6.70it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1050/1175 [02:39<00:17,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1052/1175 [02:39<00:18,  6.58it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1053/1175 [02:39<00:20,  6.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1056/1175 [02:40<00:21,  5.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1057/1175 [02:40<00:21,  5.43it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1059/1175 [02:40<00:22,  5.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1060/1175 [02:40<00:23,  5.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1061/1175 [02:41<00:22,  5.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1064/1175 [02:41<00:21,  5.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1065/1175 [02:41<00:20,  5.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1067/1175 [02:42<00:20,  5.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1069/1175 [02:42<00:20,  5.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1070/1175 [02:42<00:20,  5.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1071/1175 [02:43<00:21,  4.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████▏| 1073/1175 [02:43<00:20,  5.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████▏| 1074/1175 [02:43<00:19,  5.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████▏| 1075/1175 [02:43<00:19,  5.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1077/1175 [02:44<00:18,  5.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1079/1175 [02:44<00:15,  6.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1081/1175 [02:44<00:14,  6.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1083/1175 [02:45<00:13,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1085/1175 [02:45<00:13,  6.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1087/1175 [02:45<00:12,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1089/1175 [02:46<00:12,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1091/1175 [02:46<00:12,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1093/1175 [02:46<00:11,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1095/1175 [02:46<00:11,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1097/1175 [02:47<00:11,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▎| 1099/1175 [02:47<00:11,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▎| 1101/1175 [02:47<00:10,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1103/1175 [02:48<00:10,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1105/1175 [02:48<00:10,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1107/1175 [02:48<00:09,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1109/1175 [02:48<00:09,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1111/1175 [02:49<00:09,  6.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1113/1175 [02:49<00:09,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1115/1175 [02:49<00:08,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1117/1175 [02:50<00:08,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1119/1175 [02:50<00:08,  6.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1121/1175 [02:50<00:07,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1123/1175 [02:50<00:07,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1125/1175 [02:51<00:07,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1127/1175 [02:51<00:06,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1129/1175 [02:51<00:06,  6.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▋| 1131/1175 [02:52<00:06,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▋| 1133/1175 [02:52<00:06,  6.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1135/1175 [02:52<00:05,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1137/1175 [02:53<00:05,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1139/1175 [02:53<00:05,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1141/1175 [02:53<00:04,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1143/1175 [02:53<00:04,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1145/1175 [02:54<00:04,  6.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1146/1175 [02:54<00:04,  5.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1147/1175 [02:54<00:05,  5.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1149/1175 [02:55<00:04,  5.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1152/1175 [02:55<00:04,  5.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1154/1175 [02:56<00:04,  5.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1156/1175 [02:56<00:03,  5.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▊| 1158/1175 [02:56<00:03,  5.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▊| 1160/1175 [02:57<00:02,  5.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1161/1175 [02:57<00:02,  4.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1164/1175 [02:57<00:02,  5.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1165/1175 [02:58<00:01,  5.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1168/1175 [02:58<00:01,  5.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1170/1175 [02:59<00:00,  5.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1172/1175 [02:59<00:00,  6.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1174/1175 [02:59<00:00,  6.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|██████████| 1175/1175 [02:59<00:00,  6.54it/s]

TEXT: torch.Size([3, 384])
IMAGE: torch.Size([3, 384])
GRAPH: torch.Size([3, 384])
Epoch 2 Loss: 0.46350911964127356

  0%|          | 1/1175 [00:00<03:03,  6.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 2/1175 [00:00<02:53,  6.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 3/1175 [00:00<02:47,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 4/1175 [00:00<02:52,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 5/1175 [00:00<02:45,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 6/1175 [00:00<02:47,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 7/1175 [00:01<02:46,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 8/1175 [00:01<02:43,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 9/1175 [00:01<02:46,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 10/1175 [00:01<02:44,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 11/1175 [00:01<02:52,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 12/1175 [00:01<02:48,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 13/1175 [00:01<02:55,  6.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 14/1175 [00:02<02:52,  6.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|▏         | 15/1175 [00:02<02:47,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|▏         | 16/1175 [00:02<02:49,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|▏         | 17/1175 [00:02<02:45,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 18/1175 [00:02<02:42,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 19/1175 [00:02<02:40,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 20/1175 [00:02<02:40,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 21/1175 [00:03<02:41,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 22/1175 [00:03<02:44,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 23/1175 [00:03<02:42,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 24/1175 [00:03<02:37,  7.32it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 25/1175 [00:03<02:36,  7.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 26/1175 [00:03<02:35,  7.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 27/1175 [00:03<02:34,  7.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 28/1175 [00:03<02:35,  7.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 29/1175 [00:04<02:32,  7.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 30/1175 [00:04<02:32,  7.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 31/1175 [00:04<02:43,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 32/1175 [00:04<02:36,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 33/1175 [00:04<02:37,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 34/1175 [00:04<02:36,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 35/1175 [00:04<02:35,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 36/1175 [00:05<02:34,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 37/1175 [00:05<02:33,  7.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 38/1175 [00:05<02:37,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 39/1175 [00:05<02:41,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 40/1175 [00:05<02:46,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 41/1175 [00:05<02:41,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▎         | 42/1175 [00:05<02:40,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▎         | 43/1175 [00:06<02:38,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▎         | 44/1175 [00:06<02:36,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 45/1175 [00:06<02:35,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 46/1175 [00:06<02:39,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 47/1175 [00:06<02:37,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 48/1175 [00:06<02:43,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 49/1175 [00:06<02:39,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 50/1175 [00:07<02:36,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 51/1175 [00:07<02:36,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 52/1175 [00:07<02:37,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 53/1175 [00:07<02:39,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 54/1175 [00:07<02:38,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 55/1175 [00:07<02:38,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 56/1175 [00:07<02:36,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 57/1175 [00:08<02:39,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 58/1175 [00:08<02:35,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 59/1175 [00:08<02:33,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 60/1175 [00:08<02:36,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 61/1175 [00:08<02:36,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 62/1175 [00:08<02:38,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 63/1175 [00:08<02:40,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 65/1175 [00:09<03:13,  5.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 67/1175 [00:09<03:29,  5.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 69/1175 [00:10<03:30,  5.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 71/1175 [00:10<03:18,  5.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 73/1175 [00:10<03:12,  5.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▋         | 74/1175 [00:10<03:10,  5.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▋         | 76/1175 [00:11<03:23,  5.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 78/1175 [00:11<03:25,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 80/1175 [00:12<03:28,  5.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 82/1175 [00:12<03:16,  5.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 83/1175 [00:12<03:31,  5.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 85/1175 [00:13<03:36,  5.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 86/1175 [00:13<03:43,  4.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 89/1175 [00:13<03:08,  5.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 91/1175 [00:14<02:48,  6.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 93/1175 [00:14<02:41,  6.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 95/1175 [00:14<02:32,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 97/1175 [00:14<02:26,  7.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 99/1175 [00:15<02:25,  7.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▊         | 101/1175 [00:15<02:29,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 103/1175 [00:15<02:23,  7.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 105/1175 [00:16<02:28,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 107/1175 [00:16<02:23,  7.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 109/1175 [00:16<02:23,  7.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 111/1175 [00:16<02:26,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 113/1175 [00:17<02:27,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 115/1175 [00:17<02:18,  7.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 117/1175 [00:17<02:16,  7.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 119/1175 [00:17<02:22,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 121/1175 [00:18<02:25,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 123/1175 [00:18<02:25,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 125/1175 [00:18<02:22,  7.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 127/1175 [00:18<02:21,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 129/1175 [00:19<02:24,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 131/1175 [00:19<02:22,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█▏        | 133/1175 [00:19<02:28,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█▏        | 135/1175 [00:20<02:19,  7.43it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 137/1175 [00:20<02:26,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 139/1175 [00:20<02:21,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 141/1175 [00:20<02:18,  7.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 143/1175 [00:21<02:19,  7.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 145/1175 [00:21<02:25,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 147/1175 [00:21<02:25,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 149/1175 [00:22<02:21,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 151/1175 [00:22<02:26,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 153/1175 [00:22<02:22,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 155/1175 [00:22<02:22,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 157/1175 [00:23<02:20,  7.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▎        | 159/1175 [00:23<02:19,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▎        | 161/1175 [00:23<02:30,  6.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 162/1175 [00:23<02:49,  5.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 165/1175 [00:24<02:58,  5.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 167/1175 [00:24<02:53,  5.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 169/1175 [00:25<02:51,  5.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 170/1175 [00:25<02:57,  5.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 172/1175 [00:25<03:12,  5.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 174/1175 [00:26<03:06,  5.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 176/1175 [00:26<02:59,  5.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 178/1175 [00:26<02:52,  5.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 179/1175 [00:27<03:02,  5.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 182/1175 [00:27<03:06,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 183/1175 [00:27<03:11,  5.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 185/1175 [00:28<03:12,  5.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 187/1175 [00:28<02:52,  5.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 189/1175 [00:28<02:40,  6.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▋        | 191/1175 [00:29<02:22,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▋        | 193/1175 [00:29<02:12,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 195/1175 [00:29<02:10,  7.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 197/1175 [00:29<02:15,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 199/1175 [00:30<02:13,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 201/1175 [00:30<02:10,  7.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 203/1175 [00:30<02:09,  7.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 205/1175 [00:31<02:10,  7.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 207/1175 [00:31<02:21,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 209/1175 [00:31<02:42,  5.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 211/1175 [00:32<02:31,  6.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 213/1175 [00:32<02:20,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 215/1175 [00:32<02:15,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 217/1175 [00:32<02:09,  7.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▊        | 219/1175 [00:33<02:08,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 221/1175 [00:33<02:06,  7.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 223/1175 [00:33<02:05,  7.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 225/1175 [00:33<02:09,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 227/1175 [00:34<02:08,  7.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 229/1175 [00:34<02:06,  7.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 231/1175 [00:34<02:04,  7.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 233/1175 [00:35<02:11,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 235/1175 [00:35<02:08,  7.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 237/1175 [00:35<02:05,  7.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 239/1175 [00:35<02:03,  7.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 241/1175 [00:36<02:03,  7.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 243/1175 [00:36<02:07,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 245/1175 [00:36<02:02,  7.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 247/1175 [00:36<02:03,  7.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 249/1175 [00:37<02:07,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██▏       | 251/1175 [00:37<02:07,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 253/1175 [00:37<02:01,  7.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 255/1175 [00:37<01:59,  7.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 257/1175 [00:38<02:04,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 259/1175 [00:38<02:18,  6.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 261/1175 [00:38<02:33,  5.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 263/1175 [00:39<02:39,  5.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 265/1175 [00:39<02:36,  5.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 267/1175 [00:39<02:29,  6.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 268/1175 [00:40<02:37,  5.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 271/1175 [00:40<02:41,  5.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 273/1175 [00:41<02:40,  5.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 275/1175 [00:41<02:42,  5.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 276/1175 [00:41<02:50,  5.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▎       | 277/1175 [00:41<02:58,  5.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▎       | 278/1175 [00:42<02:58,  5.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▎       | 279/1175 [00:42<03:11,  4.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 282/1175 [00:42<02:55,  5.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 283/1175 [00:43<02:49,  5.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 286/1175 [00:43<02:48,  5.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 287/1175 [00:43<03:02,  4.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 288/1175 [00:44<03:10,  4.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 289/1175 [00:44<03:21,  4.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 290/1175 [00:44<03:29,  4.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 291/1175 [00:44<03:31,  4.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 292/1175 [00:45<03:26,  4.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 293/1175 [00:45<03:21,  4.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 294/1175 [00:45<03:35,  4.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 295/1175 [00:45<03:39,  4.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 296/1175 [00:46<03:37,  4.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 297/1175 [00:46<03:29,  4.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 298/1175 [00:46<03:24,  4.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 299/1175 [00:46<03:16,  4.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 301/1175 [00:47<03:00,  4.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 302/1175 [00:47<03:05,  4.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 303/1175 [00:47<03:09,  4.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 305/1175 [00:48<03:03,  4.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 306/1175 [00:48<03:00,  4.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 308/1175 [00:48<03:13,  4.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▋       | 309/1175 [00:48<03:20,  4.32it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▋       | 310/1175 [00:49<03:41,  3.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▋       | 311/1175 [00:49<04:06,  3.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 312/1175 [00:49<04:08,  3.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 313/1175 [00:50<04:25,  3.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 314/1175 [00:50<04:03,  3.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 315/1175 [00:50<03:52,  3.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 316/1175 [00:51<04:21,  3.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 317/1175 [00:51<04:18,  3.32it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 319/1175 [00:51<04:03,  3.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 320/1175 [00:52<04:52,  2.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 321/1175 [00:52<05:25,  2.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 322/1175 [00:53<06:15,  2.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 323/1175 [00:54<08:00,  1.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 324/1175 [00:55<09:12,  1.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 325/1175 [00:56<10:31,  1.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 326/1175 [00:57<11:46,  1.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 327/1175 [00:57<10:48,  1.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 328/1175 [00:58<11:29,  1.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 329/1175 [00:59<09:59,  1.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 330/1175 [00:59<08:00,  1.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 331/1175 [00:59<06:52,  2.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 332/1175 [00:59<05:48,  2.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 333/1175 [01:00<05:10,  2.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 334/1175 [01:00<04:37,  3.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▊       | 335/1175 [01:00<04:05,  3.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▊       | 336/1175 [01:00<03:56,  3.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 338/1175 [01:01<03:38,  3.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 339/1175 [01:01<03:58,  3.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 340/1175 [01:02<04:37,  3.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 342/1175 [01:02<03:47,  3.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 344/1175 [01:02<02:47,  4.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 346/1175 [01:03<02:21,  5.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 348/1175 [01:03<02:02,  6.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 350/1175 [01:03<01:56,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 352/1175 [01:03<01:58,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 354/1175 [01:04<01:52,  7.32it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 356/1175 [01:04<01:57,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 358/1175 [01:04<01:54,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 360/1175 [01:05<01:52,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 362/1175 [01:05<01:50,  7.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 364/1175 [01:05<01:52,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 366/1175 [01:05<01:48,  7.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███▏      | 368/1175 [01:06<01:48,  7.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███▏      | 370/1175 [01:06<01:44,  7.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 372/1175 [01:06<01:45,  7.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 374/1175 [01:06<01:51,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 376/1175 [01:07<01:47,  7.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 378/1175 [01:07<01:46,  7.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 380/1175 [01:07<01:47,  7.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 382/1175 [01:08<01:50,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 384/1175 [01:08<01:48,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 386/1175 [01:08<01:44,  7.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 388/1175 [01:08<02:03,  6.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 389/1175 [01:09<02:12,  5.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 392/1175 [01:09<02:20,  5.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▎      | 394/1175 [01:10<02:23,  5.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▎      | 395/1175 [01:10<02:29,  5.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 397/1175 [01:10<02:31,  5.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 399/1175 [01:11<02:32,  5.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 401/1175 [01:11<02:26,  5.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 403/1175 [01:11<02:20,  5.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 405/1175 [01:12<02:14,  5.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 406/1175 [01:12<02:14,  5.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 407/1175 [01:12<02:28,  5.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 408/1175 [01:12<02:37,  4.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 409/1175 [01:13<02:38,  4.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 410/1175 [01:13<02:38,  4.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 411/1175 [01:13<02:42,  4.70it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 414/1175 [01:14<02:32,  5.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 416/1175 [01:14<02:12,  5.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 418/1175 [01:14<02:00,  6.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 420/1175 [01:14<01:51,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 422/1175 [01:15<01:44,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 424/1175 [01:15<01:40,  7.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▋      | 426/1175 [01:15<01:41,  7.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▋      | 428/1175 [01:15<01:40,  7.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 430/1175 [01:16<01:37,  7.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 432/1175 [01:16<01:37,  7.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 434/1175 [01:16<01:45,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 436/1175 [01:17<01:41,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 438/1175 [01:17<01:39,  7.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 440/1175 [01:17<01:42,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 442/1175 [01:17<01:45,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 444/1175 [01:18<01:40,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 446/1175 [01:18<01:40,  7.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 448/1175 [01:18<01:40,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 450/1175 [01:19<01:39,  7.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 452/1175 [01:19<01:39,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▊      | 454/1175 [01:19<01:40,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 456/1175 [01:19<01:41,  7.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 458/1175 [01:20<01:43,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 460/1175 [01:20<01:44,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 462/1175 [01:20<01:44,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 464/1175 [01:21<01:42,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|███▉      | 466/1175 [01:21<01:40,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|███▉      | 468/1175 [01:21<01:43,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 470/1175 [01:21<01:43,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 472/1175 [01:22<01:39,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 474/1175 [01:22<01:36,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 476/1175 [01:22<01:37,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 478/1175 [01:23<01:39,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 480/1175 [01:23<01:33,  7.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 482/1175 [01:23<01:31,  7.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 484/1175 [01:23<01:37,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████▏     | 486/1175 [01:24<01:57,  5.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 488/1175 [01:24<02:01,  5.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 490/1175 [01:25<01:58,  5.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 492/1175 [01:25<01:58,  5.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 494/1175 [01:25<02:02,  5.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 496/1175 [01:26<01:58,  5.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 498/1175 [01:26<01:59,  5.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 500/1175 [01:26<01:56,  5.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 502/1175 [01:27<01:56,  5.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 504/1175 [01:27<01:55,  5.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 506/1175 [01:27<02:01,  5.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 508/1175 [01:28<02:04,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 510/1175 [01:28<02:06,  5.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▎     | 512/1175 [01:29<02:03,  5.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▎     | 514/1175 [01:29<01:44,  6.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 516/1175 [01:29<01:38,  6.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 518/1175 [01:29<01:33,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 520/1175 [01:30<01:34,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 522/1175 [01:30<01:28,  7.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 524/1175 [01:30<01:28,  7.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 526/1175 [01:30<01:34,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 528/1175 [01:31<01:33,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 530/1175 [01:31<01:33,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 532/1175 [01:31<01:28,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 534/1175 [01:32<01:26,  7.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 536/1175 [01:32<01:32,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 538/1175 [01:32<01:30,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 540/1175 [01:32<01:27,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 542/1175 [01:33<01:25,  7.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▋     | 544/1175 [01:33<01:25,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▋     | 546/1175 [01:33<01:26,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 548/1175 [01:34<01:24,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 550/1175 [01:34<01:23,  7.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 552/1175 [01:34<01:21,  7.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 554/1175 [01:34<01:26,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 556/1175 [01:35<01:26,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 558/1175 [01:35<01:25,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 560/1175 [01:35<01:22,  7.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 562/1175 [01:35<01:28,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 564/1175 [01:36<01:23,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 566/1175 [01:36<01:23,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 568/1175 [01:36<01:23,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▊     | 570/1175 [01:37<01:25,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▊     | 572/1175 [01:37<01:22,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 574/1175 [01:37<01:25,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 576/1175 [01:37<01:24,  7.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 578/1175 [01:38<01:20,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 580/1175 [01:38<01:21,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 582/1175 [01:38<01:18,  7.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 584/1175 [01:39<01:29,  6.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 586/1175 [01:39<01:39,  5.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 588/1175 [01:39<01:44,  5.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 590/1175 [01:40<01:40,  5.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 592/1175 [01:40<01:36,  6.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 594/1175 [01:40<01:36,  6.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 596/1175 [01:41<01:44,  5.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 598/1175 [01:41<01:48,  5.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 600/1175 [01:41<01:44,  5.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 602/1175 [01:42<01:47,  5.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████▏    | 603/1175 [01:42<01:50,  5.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████▏    | 604/1175 [01:42<01:57,  4.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 606/1175 [01:43<01:57,  4.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 609/1175 [01:43<01:51,  5.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 611/1175 [01:44<01:33,  6.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 613/1175 [01:44<01:28,  6.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 615/1175 [01:44<01:19,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 617/1175 [01:44<01:17,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 619/1175 [01:45<01:16,  7.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 621/1175 [01:45<01:19,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 623/1175 [01:45<01:17,  7.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 625/1175 [01:45<01:16,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 627/1175 [01:46<01:14,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▎    | 629/1175 [01:46<01:22,  6.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▎    | 631/1175 [01:46<01:16,  7.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 633/1175 [01:47<01:15,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 635/1175 [01:47<01:16,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 637/1175 [01:47<01:12,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 639/1175 [01:47<01:15,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 641/1175 [01:48<01:13,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 643/1175 [01:48<01:13,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 645/1175 [01:48<01:10,  7.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 647/1175 [01:49<01:12,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 649/1175 [01:49<01:09,  7.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 651/1175 [01:49<01:11,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 653/1175 [01:49<01:10,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 655/1175 [01:50<01:12,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 657/1175 [01:50<01:09,  7.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 659/1175 [01:50<01:09,  7.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▋    | 661/1175 [01:50<01:08,  7.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▋    | 663/1175 [01:51<01:07,  7.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 665/1175 [01:51<01:09,  7.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 667/1175 [01:51<01:07,  7.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 669/1175 [01:52<01:07,  7.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 671/1175 [01:52<01:06,  7.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 673/1175 [01:52<01:09,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 675/1175 [01:52<01:07,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 677/1175 [01:53<01:06,  7.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 679/1175 [01:53<01:05,  7.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 681/1175 [01:53<01:09,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 683/1175 [01:54<01:19,  6.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 685/1175 [01:54<01:22,  5.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 687/1175 [01:54<01:28,  5.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▊    | 689/1175 [01:55<01:28,  5.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 691/1175 [01:55<01:30,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 693/1175 [01:55<01:29,  5.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 695/1175 [01:56<01:25,  5.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 697/1175 [01:56<01:23,  5.70it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 699/1175 [01:57<01:28,  5.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 701/1175 [01:57<01:22,  5.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 703/1175 [01:57<01:23,  5.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 705/1175 [01:58<01:23,  5.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 707/1175 [01:58<01:27,  5.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 709/1175 [01:58<01:21,  5.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 711/1175 [01:59<01:12,  6.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 713/1175 [01:59<01:07,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 715/1175 [01:59<01:05,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 717/1175 [01:59<01:03,  7.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 719/1175 [02:00<01:02,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████▏   | 721/1175 [02:00<01:01,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 723/1175 [02:00<01:03,  7.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 725/1175 [02:01<01:05,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 727/1175 [02:01<01:02,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 729/1175 [02:01<01:00,  7.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 731/1175 [02:01<01:02,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 733/1175 [02:02<01:03,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 735/1175 [02:02<00:59,  7.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 737/1175 [02:02<01:03,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 739/1175 [02:03<01:01,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 741/1175 [02:03<01:01,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 743/1175 [02:03<00:59,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 745/1175 [02:03<00:57,  7.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▎   | 747/1175 [02:04<00:57,  7.43it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▎   | 749/1175 [02:04<00:59,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 751/1175 [02:04<00:58,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 753/1175 [02:04<00:58,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 755/1175 [02:05<01:01,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 757/1175 [02:05<01:01,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 759/1175 [02:05<00:59,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 761/1175 [02:06<00:58,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 763/1175 [02:06<00:58,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 765/1175 [02:06<00:58,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 767/1175 [02:06<00:56,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 769/1175 [02:07<00:55,  7.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 771/1175 [02:07<00:53,  7.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 773/1175 [02:07<00:53,  7.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 775/1175 [02:08<00:54,  7.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 777/1175 [02:08<00:53,  7.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▋   | 779/1175 [02:08<00:53,  7.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▋   | 781/1175 [02:08<01:02,  6.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 783/1175 [02:09<01:11,  5.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 785/1175 [02:09<01:07,  5.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 787/1175 [02:10<01:05,  5.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 789/1175 [02:10<01:04,  5.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 790/1175 [02:10<01:06,  5.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 792/1175 [02:10<01:11,  5.32it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 795/1175 [02:11<01:08,  5.58it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 797/1175 [02:11<01:07,  5.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 799/1175 [02:12<01:06,  5.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 801/1175 [02:12<01:08,  5.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 803/1175 [02:12<01:10,  5.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▊   | 805/1175 [02:13<01:08,  5.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▊   | 806/1175 [02:13<01:07,  5.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 809/1175 [02:14<01:01,  5.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 811/1175 [02:14<00:54,  6.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 813/1175 [02:14<00:50,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 815/1175 [02:14<00:50,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 817/1175 [02:15<00:50,  7.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 819/1175 [02:15<00:49,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 821/1175 [02:15<00:48,  7.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 823/1175 [02:15<00:48,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 825/1175 [02:16<00:48,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 827/1175 [02:16<00:47,  7.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 829/1175 [02:16<00:46,  7.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 831/1175 [02:17<00:47,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 833/1175 [02:17<00:47,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 835/1175 [02:17<00:46,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 837/1175 [02:17<00:45,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████▏  | 839/1175 [02:18<00:45,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 841/1175 [02:18<00:45,  7.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 843/1175 [02:18<00:45,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 845/1175 [02:18<00:44,  7.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 846/1175 [02:19<00:45,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 848/1175 [02:19<01:23,  3.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 850/1175 [02:20<01:05,  4.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 852/1175 [02:20<00:54,  5.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 854/1175 [02:20<00:48,  6.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 856/1175 [02:21<00:44,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 858/1175 [02:21<00:44,  7.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 860/1175 [02:21<00:43,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 862/1175 [02:21<00:41,  7.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▎  | 864/1175 [02:22<00:41,  7.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▎  | 866/1175 [02:22<00:42,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 868/1175 [02:22<00:43,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 870/1175 [02:23<00:42,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 872/1175 [02:23<00:42,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 874/1175 [02:23<00:42,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 876/1175 [02:23<00:43,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 877/1175 [02:24<00:49,  6.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 879/1175 [02:24<00:53,  5.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 881/1175 [02:24<00:52,  5.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 883/1175 [02:25<00:50,  5.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 885/1175 [02:25<00:50,  5.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 887/1175 [02:25<00:48,  5.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 889/1175 [02:26<00:47,  6.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 891/1175 [02:26<00:47,  6.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 893/1175 [02:26<00:47,  5.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 894/1175 [02:27<00:50,  5.58it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▋  | 897/1175 [02:27<00:52,  5.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 899/1175 [02:28<00:54,  5.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 900/1175 [02:28<00:55,  4.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 901/1175 [02:28<00:56,  4.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 903/1175 [02:28<00:54,  4.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 905/1175 [02:29<00:44,  6.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 907/1175 [02:29<00:39,  6.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 909/1175 [02:29<00:39,  6.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 911/1175 [02:30<00:36,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 913/1175 [02:30<00:36,  7.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 915/1175 [02:30<00:35,  7.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 917/1175 [02:30<00:35,  7.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 919/1175 [02:31<00:35,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 921/1175 [02:31<00:34,  7.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▊  | 923/1175 [02:31<00:33,  7.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▊  | 925/1175 [02:31<00:34,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 927/1175 [02:32<00:33,  7.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 929/1175 [02:32<00:33,  7.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 931/1175 [02:32<00:34,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 933/1175 [02:33<00:34,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 935/1175 [02:33<00:34,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 937/1175 [02:33<00:32,  7.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 939/1175 [02:33<00:32,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 941/1175 [02:34<00:32,  7.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 943/1175 [02:34<00:33,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 945/1175 [02:34<00:31,  7.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 947/1175 [02:35<00:31,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 949/1175 [02:35<00:30,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 951/1175 [02:35<00:29,  7.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 953/1175 [02:35<00:31,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████▏ | 955/1175 [02:36<00:30,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████▏ | 957/1175 [02:36<00:29,  7.43it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 959/1175 [02:36<00:29,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 961/1175 [02:36<00:30,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 963/1175 [02:37<00:29,  7.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 965/1175 [02:37<00:28,  7.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 967/1175 [02:37<00:29,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 969/1175 [02:38<00:30,  6.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 971/1175 [02:38<00:28,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 973/1175 [02:38<00:27,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 975/1175 [02:39<00:30,  6.58it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 977/1175 [02:39<00:32,  6.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 979/1175 [02:39<00:35,  5.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 981/1175 [02:40<00:36,  5.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▎ | 982/1175 [02:40<00:37,  5.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▎ | 984/1175 [02:40<00:38,  5.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 985/1175 [02:40<00:36,  5.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 987/1175 [02:41<00:36,  5.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 989/1175 [02:41<00:36,  5.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 991/1175 [02:42<00:35,  5.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 993/1175 [02:42<00:34,  5.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 995/1175 [02:42<00:34,  5.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 997/1175 [02:43<00:32,  5.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 999/1175 [02:43<00:32,  5.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1001/1175 [02:43<00:29,  5.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1003/1175 [02:44<00:27,  6.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1005/1175 [02:44<00:25,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1007/1175 [02:44<00:23,  7.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1009/1175 [02:45<00:23,  7.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1011/1175 [02:45<00:23,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1013/1175 [02:45<00:22,  7.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▋ | 1015/1175 [02:45<00:22,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1017/1175 [02:46<00:21,  7.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1019/1175 [02:46<00:21,  7.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1021/1175 [02:46<00:22,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1023/1175 [02:47<00:20,  7.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1025/1175 [02:47<00:20,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1027/1175 [02:47<00:20,  7.32it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1029/1175 [02:47<00:20,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1031/1175 [02:48<00:20,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1033/1175 [02:48<00:20,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1035/1175 [02:48<00:19,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1037/1175 [02:49<00:19,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1039/1175 [02:49<00:18,  7.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▊ | 1041/1175 [02:49<00:17,  7.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1043/1175 [02:49<00:18,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1045/1175 [02:50<00:18,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1047/1175 [02:50<00:18,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1049/1175 [02:50<00:17,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1051/1175 [02:50<00:17,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1053/1175 [02:51<00:16,  7.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1055/1175 [02:51<00:16,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1057/1175 [02:51<00:16,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1059/1175 [02:52<00:16,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1061/1175 [02:52<00:15,  7.32it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1063/1175 [02:52<00:15,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1065/1175 [02:52<00:15,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1067/1175 [02:53<00:14,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1069/1175 [02:53<00:14,  7.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1071/1175 [02:53<00:14,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████▏| 1073/1175 [02:54<00:16,  6.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████▏| 1075/1175 [02:54<00:18,  5.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1076/1175 [02:54<00:18,  5.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1079/1175 [02:55<00:18,  5.32it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1081/1175 [02:55<00:16,  5.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1083/1175 [02:56<00:16,  5.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1085/1175 [02:56<00:17,  5.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1087/1175 [02:56<00:15,  5.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1088/1175 [02:56<00:16,  5.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1089/1175 [02:57<00:17,  5.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1092/1175 [02:57<00:15,  5.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1094/1175 [02:58<00:15,  5.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1095/1175 [02:58<00:15,  5.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1097/1175 [02:58<00:14,  5.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▎| 1099/1175 [02:59<00:13,  5.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▎| 1101/1175 [02:59<00:11,  6.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1103/1175 [02:59<00:10,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1105/1175 [02:59<00:10,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1107/1175 [03:00<00:09,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1109/1175 [03:00<00:10,  6.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1111/1175 [03:00<00:09,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1113/1175 [03:01<00:08,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1115/1175 [03:01<00:08,  7.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1117/1175 [03:01<00:08,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1119/1175 [03:01<00:07,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1121/1175 [03:02<00:07,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1123/1175 [03:02<00:07,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1125/1175 [03:02<00:07,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1127/1175 [03:03<00:07,  6.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1129/1175 [03:03<00:06,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▋| 1131/1175 [03:03<00:06,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▋| 1133/1175 [03:03<00:05,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1135/1175 [03:04<00:05,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1137/1175 [03:04<00:05,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1139/1175 [03:04<00:05,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1141/1175 [03:05<00:04,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1143/1175 [03:05<00:04,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1145/1175 [03:05<00:04,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1147/1175 [03:05<00:04,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1149/1175 [03:06<00:03,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1151/1175 [03:06<00:03,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1153/1175 [03:06<00:03,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1155/1175 [03:07<00:02,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1157/1175 [03:07<00:02,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▊| 1159/1175 [03:07<00:02,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1161/1175 [03:07<00:01,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1163/1175 [03:08<00:01,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1165/1175 [03:08<00:01,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1167/1175 [03:08<00:01,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1169/1175 [03:09<00:00,  6.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1171/1175 [03:09<00:00,  5.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1172/1175 [03:09<00:00,  5.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1174/1175 [03:10<00:00,  5.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|██████████| 1175/1175 [03:10<00:00,  6.18it/s]

TEXT: torch.Size([3, 384])
IMAGE: torch.Size([3, 384])
GRAPH: torch.Size([3, 384])
Epoch 3 Loss: 0.44361574361298944

  0%|          | 0/1175 [00:00<?, ?it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 2/1175 [00:00<04:07,  4.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 3/1175 [00:00<04:23,  4.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 5/1175 [00:01<03:50,  5.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 8/1175 [00:01<03:39,  5.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 9/1175 [00:01<03:56,  4.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 12/1175 [00:02<03:46,  5.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 13/1175 [00:02<03:39,  5.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|▏         | 16/1175 [00:03<03:45,  5.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|▏         | 17/1175 [00:03<03:41,  5.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 20/1175 [00:03<03:42,  5.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 22/1175 [00:04<03:04,  6.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 24/1175 [00:04<02:53,  6.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 26/1175 [00:04<02:43,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 28/1175 [00:05<02:41,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 30/1175 [00:05<02:38,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 32/1175 [00:05<02:36,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 34/1175 [00:05<02:41,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 36/1175 [00:06<02:44,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 38/1175 [00:06<02:46,  6.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 40/1175 [00:06<02:46,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▎         | 42/1175 [00:07<02:56,  6.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▎         | 44/1175 [00:07<02:50,  6.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 46/1175 [00:07<02:43,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 48/1175 [00:07<02:41,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 50/1175 [00:08<02:44,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 52/1175 [00:08<02:40,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 54/1175 [00:08<02:38,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 56/1175 [00:09<02:40,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 58/1175 [00:09<02:41,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 60/1175 [00:09<02:37,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 62/1175 [00:09<02:35,  7.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 64/1175 [00:10<02:41,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 66/1175 [00:10<02:33,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 68/1175 [00:10<02:38,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 70/1175 [00:11<02:35,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 72/1175 [00:11<02:39,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▋         | 74/1175 [00:11<02:34,  7.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▋         | 76/1175 [00:11<02:34,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 78/1175 [00:12<02:40,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 80/1175 [00:12<02:31,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 82/1175 [00:12<02:28,  7.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 84/1175 [00:13<02:25,  7.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 86/1175 [00:13<02:37,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 88/1175 [00:13<02:31,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 90/1175 [00:13<02:35,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 91/1175 [00:14<02:48,  6.43it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 94/1175 [00:14<03:11,  5.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 96/1175 [00:15<03:18,  5.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 98/1175 [00:15<03:11,  5.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▊         | 100/1175 [00:15<03:05,  5.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▊         | 102/1175 [00:16<02:59,  5.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 103/1175 [00:16<03:04,  5.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 106/1175 [00:16<03:17,  5.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 108/1175 [00:17<03:10,  5.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 110/1175 [00:17<03:12,  5.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 111/1175 [00:17<03:11,  5.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 113/1175 [00:18<03:20,  5.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 116/1175 [00:18<03:19,  5.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 117/1175 [00:18<03:20,  5.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 120/1175 [00:19<02:56,  5.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 122/1175 [00:19<02:44,  6.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 124/1175 [00:20<02:40,  6.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 126/1175 [00:20<02:29,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 128/1175 [00:20<02:26,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 130/1175 [00:20<02:30,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 132/1175 [00:21<02:28,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█▏        | 134/1175 [00:21<02:27,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 136/1175 [00:21<02:23,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 138/1175 [00:21<02:25,  7.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 140/1175 [00:22<02:26,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 142/1175 [00:22<02:27,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 144/1175 [00:22<02:23,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 146/1175 [00:23<02:34,  6.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 148/1175 [00:23<02:28,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 150/1175 [00:23<02:24,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 152/1175 [00:23<02:20,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 154/1175 [00:24<02:22,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 156/1175 [00:24<02:26,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 158/1175 [00:24<02:20,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▎        | 160/1175 [00:25<02:21,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 162/1175 [00:25<02:21,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 164/1175 [00:25<02:19,  7.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 166/1175 [00:25<02:22,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 168/1175 [00:26<02:20,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 170/1175 [00:26<02:18,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 172/1175 [00:26<02:16,  7.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 174/1175 [00:27<02:21,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 176/1175 [00:27<02:23,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 178/1175 [00:27<02:19,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 180/1175 [00:27<02:19,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 182/1175 [00:28<02:20,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 184/1175 [00:28<02:22,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 186/1175 [00:28<02:17,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 188/1175 [00:29<02:15,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 189/1175 [00:29<02:26,  6.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 190/1175 [00:29<02:45,  5.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▋        | 192/1175 [00:29<02:49,  5.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 195/1175 [00:30<03:03,  5.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 197/1175 [00:30<02:59,  5.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 199/1175 [00:31<02:51,  5.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 201/1175 [00:31<02:58,  5.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 203/1175 [00:31<03:01,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 205/1175 [00:32<02:55,  5.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 207/1175 [00:32<02:44,  5.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 208/1175 [00:32<02:52,  5.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 209/1175 [00:32<03:07,  5.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 210/1175 [00:33<03:42,  4.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 212/1175 [00:33<03:48,  4.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 213/1175 [00:33<03:36,  4.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 216/1175 [00:34<03:15,  4.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▊        | 218/1175 [00:34<02:45,  5.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▊        | 220/1175 [00:35<02:28,  6.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 222/1175 [00:35<02:19,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 224/1175 [00:35<02:15,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 226/1175 [00:35<02:15,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 228/1175 [00:36<02:17,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 230/1175 [00:36<02:14,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 232/1175 [00:36<02:18,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 234/1175 [00:37<02:15,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 236/1175 [00:37<02:13,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 238/1175 [00:37<02:11,  7.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 240/1175 [00:37<02:10,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 242/1175 [00:38<02:11,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 244/1175 [00:38<02:14,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 246/1175 [00:38<02:07,  7.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 248/1175 [00:39<02:07,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██▏       | 250/1175 [00:39<02:15,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██▏       | 252/1175 [00:39<02:12,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 254/1175 [00:40<02:11,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 256/1175 [00:40<02:14,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 258/1175 [00:40<02:09,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 260/1175 [00:40<02:05,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 262/1175 [00:41<02:09,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 264/1175 [00:41<02:09,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 266/1175 [00:41<02:09,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 268/1175 [00:42<02:09,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 270/1175 [00:42<02:11,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 272/1175 [00:42<02:06,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 274/1175 [00:42<02:04,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 276/1175 [00:43<02:02,  7.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▎       | 278/1175 [00:43<02:08,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 280/1175 [00:43<02:08,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 282/1175 [00:43<02:05,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 284/1175 [00:44<02:04,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 286/1175 [00:44<02:08,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 287/1175 [00:44<02:27,  6.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 288/1175 [00:45<02:43,  5.43it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 289/1175 [00:45<03:01,  4.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 290/1175 [00:45<03:23,  4.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 291/1175 [00:45<03:20,  4.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 294/1175 [00:46<02:53,  5.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 296/1175 [00:46<02:44,  5.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 297/1175 [00:46<02:55,  4.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 298/1175 [00:47<03:00,  4.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 299/1175 [00:47<03:04,  4.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 300/1175 [00:47<03:03,  4.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 303/1175 [00:48<02:53,  5.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 304/1175 [00:48<02:55,  4.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 305/1175 [00:48<02:57,  4.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 306/1175 [00:48<03:11,  4.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 307/1175 [00:49<03:13,  4.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 308/1175 [00:49<03:10,  4.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▋       | 310/1175 [00:49<02:55,  4.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 313/1175 [00:50<02:41,  5.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 315/1175 [00:50<02:41,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 317/1175 [00:50<02:18,  6.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 319/1175 [00:51<02:09,  6.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 321/1175 [00:51<02:04,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 323/1175 [00:51<02:03,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 325/1175 [00:52<02:07,  6.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 327/1175 [00:52<02:01,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 329/1175 [00:52<02:01,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 331/1175 [00:52<02:06,  6.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 333/1175 [00:53<02:05,  6.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▊       | 335/1175 [00:53<02:07,  6.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▊       | 337/1175 [00:53<02:04,  6.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 339/1175 [00:54<02:03,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 341/1175 [00:54<02:06,  6.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 343/1175 [00:54<02:01,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 345/1175 [00:55<02:01,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 347/1175 [00:55<02:05,  6.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 349/1175 [00:55<02:04,  6.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 351/1175 [00:55<02:00,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 353/1175 [00:56<01:58,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 355/1175 [00:56<01:59,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 357/1175 [00:56<01:54,  7.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 359/1175 [00:57<01:58,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 361/1175 [00:57<01:58,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 363/1175 [00:57<01:57,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 365/1175 [00:57<02:02,  6.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 367/1175 [00:58<02:03,  6.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███▏      | 369/1175 [00:58<02:06,  6.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 371/1175 [00:58<02:04,  6.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 373/1175 [00:59<02:00,  6.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 375/1175 [00:59<02:05,  6.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 377/1175 [00:59<02:03,  6.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 379/1175 [01:00<02:00,  6.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 381/1175 [01:00<02:01,  6.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 382/1175 [01:00<02:24,  5.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 383/1175 [01:00<02:42,  4.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 384/1175 [01:01<02:43,  4.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 385/1175 [01:01<02:50,  4.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 386/1175 [01:01<03:02,  4.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 388/1175 [01:02<02:53,  4.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 389/1175 [01:02<02:53,  4.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 390/1175 [01:02<02:59,  4.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 392/1175 [01:02<02:53,  4.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▎      | 394/1175 [01:03<02:44,  4.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▎      | 396/1175 [01:03<02:38,  4.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 398/1175 [01:04<02:26,  5.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 400/1175 [01:04<02:21,  5.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 401/1175 [01:04<02:34,  5.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 404/1175 [01:05<02:27,  5.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 406/1175 [01:05<02:20,  5.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 407/1175 [01:05<02:20,  5.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 408/1175 [01:06<02:28,  5.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 410/1175 [01:06<02:26,  5.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 412/1175 [01:06<02:07,  5.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 414/1175 [01:07<02:00,  6.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 416/1175 [01:07<01:52,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 418/1175 [01:07<01:50,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 420/1175 [01:07<01:50,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 422/1175 [01:08<01:56,  6.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 424/1175 [01:08<01:50,  6.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▋      | 426/1175 [01:08<01:50,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▋      | 428/1175 [01:09<01:52,  6.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 430/1175 [01:09<01:52,  6.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 432/1175 [01:09<01:55,  6.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 434/1175 [01:10<01:50,  6.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 436/1175 [01:10<01:52,  6.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 438/1175 [01:10<01:50,  6.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 440/1175 [01:10<01:46,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 442/1175 [01:11<01:49,  6.70it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 444/1175 [01:11<01:45,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 446/1175 [01:11<01:46,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 448/1175 [01:12<01:44,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 450/1175 [01:12<01:50,  6.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 452/1175 [01:12<01:49,  6.58it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▊      | 454/1175 [01:13<01:49,  6.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 456/1175 [01:13<01:52,  6.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 458/1175 [01:13<01:43,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 460/1175 [01:13<01:42,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 462/1175 [01:14<01:46,  6.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 464/1175 [01:14<01:45,  6.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|███▉      | 466/1175 [01:14<01:42,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|███▉      | 468/1175 [01:15<01:43,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 470/1175 [01:15<01:45,  6.70it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 472/1175 [01:15<01:44,  6.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 474/1175 [01:16<01:41,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 476/1175 [01:16<01:40,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 478/1175 [01:16<02:00,  5.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 480/1175 [01:17<02:12,  5.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 481/1175 [01:17<02:17,  5.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 483/1175 [01:17<02:13,  5.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████▏     | 485/1175 [01:18<02:14,  5.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████▏     | 487/1175 [01:18<02:12,  5.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 488/1175 [01:18<02:19,  4.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 491/1175 [01:19<02:12,  5.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 492/1175 [01:19<02:22,  4.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 493/1175 [01:19<02:28,  4.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 494/1175 [01:20<02:34,  4.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 495/1175 [01:20<02:32,  4.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 496/1175 [01:20<02:35,  4.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 497/1175 [01:20<02:33,  4.43it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 499/1175 [01:21<02:23,  4.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 500/1175 [01:21<02:16,  4.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 501/1175 [01:21<02:19,  4.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 504/1175 [01:22<01:57,  5.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 506/1175 [01:22<01:47,  6.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 508/1175 [01:22<01:41,  6.58it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 510/1175 [01:22<01:39,  6.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▎     | 512/1175 [01:23<01:36,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▎     | 514/1175 [01:23<01:34,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 516/1175 [01:23<01:41,  6.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 518/1175 [01:24<01:39,  6.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 520/1175 [01:24<01:35,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 522/1175 [01:24<01:35,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 524/1175 [01:24<01:35,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 526/1175 [01:25<01:32,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 528/1175 [01:25<01:32,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 530/1175 [01:25<01:36,  6.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 532/1175 [01:26<01:35,  6.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 534/1175 [01:26<01:32,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 536/1175 [01:26<01:31,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 538/1175 [01:27<01:31,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 540/1175 [01:27<01:33,  6.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 542/1175 [01:27<01:30,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▋     | 544/1175 [01:27<01:30,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▋     | 546/1175 [01:28<01:36,  6.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 548/1175 [01:28<01:34,  6.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 550/1175 [01:28<01:31,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 552/1175 [01:29<01:29,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 554/1175 [01:29<01:29,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 556/1175 [01:29<01:32,  6.70it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 558/1175 [01:29<01:28,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 560/1175 [01:30<01:29,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 562/1175 [01:30<01:29,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 564/1175 [01:30<01:35,  6.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 566/1175 [01:31<01:32,  6.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 568/1175 [01:31<01:31,  6.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▊     | 570/1175 [01:31<01:30,  6.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▊     | 572/1175 [01:32<01:48,  5.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 574/1175 [01:32<01:58,  5.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 575/1175 [01:32<02:03,  4.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 576/1175 [01:33<02:05,  4.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 578/1175 [01:33<02:03,  4.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 579/1175 [01:33<02:04,  4.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 580/1175 [01:33<02:07,  4.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 581/1175 [01:34<02:08,  4.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 584/1175 [01:34<01:59,  4.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 585/1175 [01:34<01:59,  4.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 586/1175 [01:35<02:01,  4.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 587/1175 [01:35<02:10,  4.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 588/1175 [01:35<02:08,  4.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 589/1175 [01:35<02:11,  4.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 590/1175 [01:36<02:14,  4.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 592/1175 [01:36<02:06,  4.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 595/1175 [01:37<02:02,  4.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 597/1175 [01:37<01:41,  5.70it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 599/1175 [01:37<01:36,  5.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 601/1175 [01:38<01:28,  6.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████▏    | 603/1175 [01:38<01:24,  6.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████▏    | 605/1175 [01:38<01:23,  6.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 607/1175 [01:38<01:28,  6.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 609/1175 [01:39<01:23,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 611/1175 [01:39<01:21,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 613/1175 [01:39<01:23,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 615/1175 [01:40<01:20,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 617/1175 [01:40<01:23,  6.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 619/1175 [01:40<01:22,  6.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 621/1175 [01:41<01:24,  6.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 623/1175 [01:41<01:25,  6.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 625/1175 [01:41<01:22,  6.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 627/1175 [01:41<01:20,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▎    | 629/1175 [01:42<01:19,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▎    | 631/1175 [01:42<01:17,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 633/1175 [01:42<01:18,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 635/1175 [01:43<01:17,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 637/1175 [01:43<01:18,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 639/1175 [01:43<01:16,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 641/1175 [01:44<01:21,  6.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 643/1175 [01:44<01:17,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 645/1175 [01:44<01:16,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 647/1175 [01:44<01:17,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 649/1175 [01:45<01:16,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 651/1175 [01:45<01:16,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 653/1175 [01:45<01:15,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 655/1175 [01:46<01:14,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 657/1175 [01:46<01:14,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 659/1175 [01:46<01:17,  6.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▋    | 661/1175 [01:46<01:14,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▋    | 662/1175 [01:47<01:15,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▋    | 663/1175 [01:47<01:25,  5.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 665/1175 [01:47<01:33,  5.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 666/1175 [01:47<01:39,  5.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 668/1175 [01:48<01:39,  5.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 670/1175 [01:48<01:32,  5.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 672/1175 [01:49<01:27,  5.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 674/1175 [01:49<01:24,  5.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 676/1175 [01:49<01:31,  5.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 677/1175 [01:49<01:33,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 680/1175 [01:50<01:32,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 682/1175 [01:50<01:27,  5.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 683/1175 [01:51<01:25,  5.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 684/1175 [01:51<01:34,  5.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 686/1175 [01:51<01:35,  5.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▊    | 688/1175 [01:52<01:35,  5.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▊    | 689/1175 [01:52<01:38,  4.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▊    | 690/1175 [01:52<01:48,  4.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 692/1175 [01:52<01:41,  4.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 694/1175 [01:53<01:23,  5.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 696/1175 [01:53<01:13,  6.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 698/1175 [01:53<01:13,  6.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 700/1175 [01:54<01:13,  6.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 702/1175 [01:54<01:11,  6.58it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 704/1175 [01:54<01:10,  6.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 706/1175 [01:55<01:08,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 708/1175 [01:55<01:07,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 710/1175 [01:55<01:07,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 712/1175 [01:55<01:07,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 714/1175 [01:56<01:05,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 716/1175 [01:56<01:03,  7.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 718/1175 [01:56<01:05,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████▏   | 720/1175 [01:57<01:03,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████▏   | 722/1175 [01:57<01:03,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 724/1175 [01:57<01:03,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 726/1175 [01:57<01:06,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 728/1175 [01:58<01:06,  6.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 730/1175 [01:58<01:04,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 732/1175 [01:58<01:03,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 734/1175 [01:59<01:03,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 736/1175 [01:59<01:04,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 738/1175 [01:59<01:04,  6.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 740/1175 [01:59<01:03,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 742/1175 [02:00<01:04,  6.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 744/1175 [02:00<01:03,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 746/1175 [02:00<01:02,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▎   | 748/1175 [02:01<01:01,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 750/1175 [02:01<01:00,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 752/1175 [02:01<00:58,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 754/1175 [02:01<00:58,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 756/1175 [02:02<00:59,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 758/1175 [02:02<00:59,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 760/1175 [02:02<00:59,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 762/1175 [02:03<01:08,  6.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 764/1175 [02:03<01:08,  5.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 766/1175 [02:03<01:09,  5.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 767/1175 [02:04<01:14,  5.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 768/1175 [02:04<01:21,  4.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 769/1175 [02:04<01:24,  4.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 772/1175 [02:05<01:18,  5.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 773/1175 [02:05<01:14,  5.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 776/1175 [02:05<01:16,  5.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 778/1175 [02:06<01:19,  5.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▋   | 780/1175 [02:06<01:20,  4.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 782/1175 [02:07<01:14,  5.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 784/1175 [02:07<01:10,  5.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 785/1175 [02:07<01:19,  4.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 788/1175 [02:08<01:11,  5.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 790/1175 [02:08<01:01,  6.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 792/1175 [02:08<00:57,  6.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 794/1175 [02:09<00:55,  6.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 796/1175 [02:09<00:53,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 798/1175 [02:09<00:52,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 800/1175 [02:09<00:51,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 802/1175 [02:10<00:53,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 804/1175 [02:10<00:52,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▊   | 806/1175 [02:10<00:53,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 808/1175 [02:11<00:52,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 810/1175 [02:11<00:50,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 812/1175 [02:11<00:51,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 814/1175 [02:11<00:51,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 816/1175 [02:12<00:50,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 818/1175 [02:12<00:50,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 820/1175 [02:12<00:52,  6.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 822/1175 [02:13<00:51,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 824/1175 [02:13<00:51,  6.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 826/1175 [02:13<00:50,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 828/1175 [02:14<00:53,  6.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 830/1175 [02:14<00:51,  6.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 832/1175 [02:14<00:50,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 834/1175 [02:14<00:49,  6.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 836/1175 [02:15<00:49,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████▏  | 838/1175 [02:15<00:47,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████▏  | 840/1175 [02:15<00:46,  7.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 842/1175 [02:16<00:46,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 844/1175 [02:16<00:46,  7.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 846/1175 [02:16<00:47,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 848/1175 [02:16<00:46,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 850/1175 [02:17<00:46,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 852/1175 [02:17<00:46,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 854/1175 [02:17<00:46,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 856/1175 [02:18<00:47,  6.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 857/1175 [02:18<00:52,  6.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 858/1175 [02:18<00:58,  5.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 859/1175 [02:18<01:03,  5.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 861/1175 [02:19<01:02,  5.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 862/1175 [02:19<01:03,  4.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▎  | 865/1175 [02:19<01:02,  4.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 867/1175 [02:20<01:02,  4.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 869/1175 [02:20<01:00,  5.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 871/1175 [02:21<01:00,  4.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 873/1175 [02:21<00:58,  5.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 875/1175 [02:21<00:52,  5.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 877/1175 [02:22<00:51,  5.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 878/1175 [02:22<00:56,  5.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 879/1175 [02:22<01:00,  4.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 882/1175 [02:23<00:57,  5.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 884/1175 [02:23<00:52,  5.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 886/1175 [02:23<00:45,  6.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 888/1175 [02:24<00:47,  6.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 890/1175 [02:24<00:44,  6.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 892/1175 [02:24<00:41,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 894/1175 [02:25<00:39,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▋  | 896/1175 [02:25<00:40,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▋  | 898/1175 [02:25<00:40,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 900/1175 [02:25<00:38,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 902/1175 [02:26<00:37,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 904/1175 [02:26<00:37,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 906/1175 [02:26<00:38,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 908/1175 [02:27<00:37,  7.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 910/1175 [02:27<00:37,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 912/1175 [02:27<00:37,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 914/1175 [02:28<00:38,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 916/1175 [02:28<00:36,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 918/1175 [02:28<00:36,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 920/1175 [02:28<00:37,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 922/1175 [02:29<00:35,  7.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▊  | 924/1175 [02:29<00:34,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 926/1175 [02:29<00:35,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 928/1175 [02:29<00:33,  7.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 930/1175 [02:30<00:34,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 932/1175 [02:30<00:33,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 934/1175 [02:30<00:34,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 936/1175 [02:31<00:32,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 938/1175 [02:31<00:32,  7.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 940/1175 [02:31<00:32,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 942/1175 [02:31<00:32,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 944/1175 [02:32<00:31,  7.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 946/1175 [02:32<00:31,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 948/1175 [02:32<00:32,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 950/1175 [02:33<00:32,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 952/1175 [02:33<00:31,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 954/1175 [02:33<00:38,  5.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████▏ | 955/1175 [02:34<00:39,  5.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████▏ | 956/1175 [02:34<00:41,  5.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 959/1175 [02:34<00:41,  5.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 960/1175 [02:35<00:43,  4.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 963/1175 [02:35<00:38,  5.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 964/1175 [02:35<00:41,  5.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 967/1175 [02:36<00:39,  5.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 969/1175 [02:36<00:38,  5.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 970/1175 [02:36<00:38,  5.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 972/1175 [02:37<00:38,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 973/1175 [02:37<00:41,  4.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 975/1175 [02:37<00:39,  5.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 976/1175 [02:38<00:39,  4.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 978/1175 [02:38<00:42,  4.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 979/1175 [02:38<00:42,  4.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▎ | 982/1175 [02:39<00:33,  5.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▎ | 984/1175 [02:39<00:31,  6.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 986/1175 [02:39<00:28,  6.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 988/1175 [02:40<00:26,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 990/1175 [02:40<00:26,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 992/1175 [02:40<00:27,  6.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 994/1175 [02:41<00:25,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 996/1175 [02:41<00:25,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 998/1175 [02:41<00:25,  6.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1000/1175 [02:41<00:24,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1002/1175 [02:42<00:23,  7.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1004/1175 [02:42<00:23,  7.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1006/1175 [02:42<00:24,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1008/1175 [02:43<00:23,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1010/1175 [02:43<00:22,  7.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1012/1175 [02:43<00:22,  7.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▋ | 1014/1175 [02:43<00:22,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▋ | 1016/1175 [02:44<00:22,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1018/1175 [02:44<00:21,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1020/1175 [02:44<00:21,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1022/1175 [02:45<00:21,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1024/1175 [02:45<00:21,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1026/1175 [02:45<00:21,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1028/1175 [02:45<00:21,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1030/1175 [02:46<00:20,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1032/1175 [02:46<00:21,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1034/1175 [02:46<00:20,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1036/1175 [02:47<00:20,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1038/1175 [02:47<00:19,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▊ | 1040/1175 [02:47<00:19,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▊ | 1042/1175 [02:47<00:18,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1044/1175 [02:48<00:18,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1046/1175 [02:48<00:18,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1048/1175 [02:48<00:17,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1050/1175 [02:49<00:20,  6.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1052/1175 [02:49<00:21,  5.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1053/1175 [02:49<00:23,  5.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1056/1175 [02:50<00:23,  4.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1057/1175 [02:50<00:25,  4.70it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1058/1175 [02:50<00:25,  4.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1059/1175 [02:51<00:25,  4.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1060/1175 [02:51<00:26,  4.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1061/1175 [02:51<00:25,  4.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1062/1175 [02:51<00:25,  4.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1064/1175 [02:52<00:24,  4.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1065/1175 [02:52<00:24,  4.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1067/1175 [02:52<00:22,  4.70it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1069/1175 [02:53<00:20,  5.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1070/1175 [02:53<00:21,  4.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1071/1175 [02:53<00:21,  4.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████▏| 1073/1175 [02:54<00:20,  4.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████▏| 1075/1175 [02:54<00:30,  3.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1077/1175 [02:55<00:21,  4.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1079/1175 [02:55<00:18,  5.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1081/1175 [02:55<00:15,  6.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1083/1175 [02:56<00:13,  6.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1085/1175 [02:56<00:13,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1087/1175 [02:56<00:12,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1089/1175 [02:56<00:12,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1091/1175 [02:57<00:12,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1093/1175 [02:57<00:11,  7.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1095/1175 [02:57<00:11,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1097/1175 [02:58<00:11,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▎| 1099/1175 [02:58<00:11,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▎| 1101/1175 [02:58<00:10,  6.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1103/1175 [02:58<00:10,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1105/1175 [02:59<00:10,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1107/1175 [02:59<00:09,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1109/1175 [02:59<00:09,  6.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1111/1175 [03:00<00:09,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1113/1175 [03:00<00:09,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1115/1175 [03:00<00:08,  6.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1117/1175 [03:01<00:08,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1119/1175 [03:01<00:07,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1121/1175 [03:01<00:07,  7.17it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1123/1175 [03:01<00:07,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1125/1175 [03:02<00:07,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1127/1175 [03:02<00:06,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1129/1175 [03:02<00:06,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▋| 1131/1175 [03:03<00:06,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▋| 1133/1175 [03:03<00:06,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1135/1175 [03:03<00:05,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1137/1175 [03:03<00:05,  6.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1139/1175 [03:04<00:05,  6.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1141/1175 [03:04<00:06,  5.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1143/1175 [03:05<00:06,  5.22it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1145/1175 [03:05<00:05,  5.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1147/1175 [03:05<00:04,  5.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1149/1175 [03:06<00:04,  5.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1151/1175 [03:06<00:04,  5.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1153/1175 [03:07<00:04,  5.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1154/1175 [03:07<00:04,  5.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1157/1175 [03:07<00:03,  5.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▊| 1158/1175 [03:07<00:03,  5.56it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▊| 1160/1175 [03:08<00:02,  5.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1161/1175 [03:08<00:02,  5.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1163/1175 [03:08<00:02,  5.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1164/1175 [03:09<00:02,  4.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1165/1175 [03:09<00:02,  4.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1166/1175 [03:09<00:02,  4.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1168/1175 [03:09<00:01,  4.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1170/1175 [03:10<00:00,  5.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1172/1175 [03:10<00:00,  6.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1174/1175 [03:10<00:00,  6.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|██████████| 1175/1175 [03:10<00:00,  6.15it/s]

TEXT: torch.Size([3, 384])
IMAGE: torch.Size([3, 384])
GRAPH: torch.Size([3, 384])
Epoch 4 Loss: 0.42504144188571485

  0%|          | 2/1175 [00:00<03:12,  6.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  0%|          | 4/1175 [00:00<02:56,  6.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 6/1175 [00:00<02:48,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 8/1175 [00:01<02:44,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 10/1175 [00:01<02:50,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 12/1175 [00:01<02:48,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|          | 14/1175 [00:02<02:45,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  1%|▏         | 16/1175 [00:02<02:42,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 18/1175 [00:02<02:49,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 20/1175 [00:02<02:46,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 22/1175 [00:03<02:42,  7.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 24/1175 [00:03<02:42,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 26/1175 [00:03<02:48,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 28/1175 [00:04<02:53,  6.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 30/1175 [00:04<02:44,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 32/1175 [00:04<02:47,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 34/1175 [00:04<02:42,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 36/1175 [00:05<02:43,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 38/1175 [00:05<02:42,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 40/1175 [00:05<02:43,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▎         | 42/1175 [00:06<02:42,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▎         | 44/1175 [00:06<02:38,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 46/1175 [00:06<02:42,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 48/1175 [00:07<02:43,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 50/1175 [00:07<02:37,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 52/1175 [00:07<02:36,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 54/1175 [00:07<02:43,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 56/1175 [00:08<02:39,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 58/1175 [00:08<02:37,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 60/1175 [00:08<02:35,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 62/1175 [00:09<02:50,  6.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 64/1175 [00:09<03:21,  5.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 65/1175 [00:09<03:26,  5.38it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 68/1175 [00:10<03:36,  5.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 69/1175 [00:10<03:43,  4.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 71/1175 [00:10<03:41,  4.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 72/1175 [00:11<04:02,  4.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▋         | 74/1175 [00:11<03:53,  4.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▋         | 76/1175 [00:11<03:33,  5.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 77/1175 [00:12<03:29,  5.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 80/1175 [00:12<03:20,  5.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 82/1175 [00:13<03:30,  5.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 84/1175 [00:13<03:35,  5.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 85/1175 [00:13<03:51,  4.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 86/1175 [00:13<03:53,  4.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 87/1175 [00:14<04:03,  4.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 89/1175 [00:14<03:37,  5.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 91/1175 [00:14<03:03,  5.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 93/1175 [00:15<02:47,  6.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 95/1175 [00:15<02:44,  6.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 97/1175 [00:15<02:37,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 99/1175 [00:16<02:34,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▊         | 101/1175 [00:16<02:33,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 103/1175 [00:16<02:36,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 105/1175 [00:16<02:37,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 107/1175 [00:17<02:39,  6.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 109/1175 [00:17<02:38,  6.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 111/1175 [00:17<02:36,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 113/1175 [00:18<02:33,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 115/1175 [00:18<02:29,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 117/1175 [00:18<02:32,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 119/1175 [00:18<02:28,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 121/1175 [00:19<02:29,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 123/1175 [00:19<02:30,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 125/1175 [00:19<02:36,  6.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 127/1175 [00:20<02:32,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 129/1175 [00:20<02:27,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 131/1175 [00:20<02:34,  6.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█▏        | 133/1175 [00:20<02:31,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█▏        | 135/1175 [00:21<02:34,  6.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 137/1175 [00:21<02:31,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 139/1175 [00:21<02:33,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 141/1175 [00:22<02:29,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 143/1175 [00:22<02:32,  6.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 145/1175 [00:22<02:38,  6.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 147/1175 [00:23<02:29,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 149/1175 [00:23<02:27,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 151/1175 [00:23<02:28,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 153/1175 [00:23<02:27,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 155/1175 [00:24<02:26,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 156/1175 [00:24<02:30,  6.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 157/1175 [00:24<02:48,  6.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 158/1175 [00:24<03:02,  5.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▎        | 160/1175 [00:25<03:23,  4.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 163/1175 [00:25<03:23,  4.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 164/1175 [00:26<03:24,  4.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 167/1175 [00:26<03:21,  5.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 168/1175 [00:26<03:22,  4.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 170/1175 [00:27<03:21,  4.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 172/1175 [00:27<03:06,  5.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 173/1175 [00:27<03:10,  5.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 175/1175 [00:28<03:18,  5.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 176/1175 [00:28<03:22,  4.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 177/1175 [00:28<03:34,  4.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 178/1175 [00:28<03:43,  4.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 179/1175 [00:29<03:42,  4.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 180/1175 [00:29<03:45,  4.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 183/1175 [00:29<03:03,  5.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 185/1175 [00:30<02:40,  6.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 187/1175 [00:30<02:33,  6.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 189/1175 [00:30<02:24,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▋        | 191/1175 [00:31<02:19,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▋        | 193/1175 [00:31<02:21,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 195/1175 [00:31<02:24,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 197/1175 [00:31<02:16,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 199/1175 [00:32<02:17,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 201/1175 [00:32<02:21,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 203/1175 [00:32<02:18,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 205/1175 [00:33<02:17,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 207/1175 [00:33<02:23,  6.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 209/1175 [00:33<02:20,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 211/1175 [00:33<02:18,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 213/1175 [00:34<02:22,  6.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 215/1175 [00:34<02:22,  6.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 217/1175 [00:34<02:18,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▊        | 219/1175 [00:35<02:16,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 221/1175 [00:35<02:19,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 223/1175 [00:35<02:24,  6.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 225/1175 [00:36<02:17,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 227/1175 [00:36<02:16,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 229/1175 [00:36<02:18,  6.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 231/1175 [00:36<02:18,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|█▉        | 233/1175 [00:37<02:13,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 235/1175 [00:37<02:09,  7.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 237/1175 [00:37<02:14,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 239/1175 [00:38<02:15,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 241/1175 [00:38<02:14,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 243/1175 [00:38<02:14,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 245/1175 [00:38<02:17,  6.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 246/1175 [00:39<02:20,  6.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 249/1175 [00:39<02:55,  5.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██▏       | 251/1175 [00:40<03:01,  5.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██▏       | 252/1175 [00:40<03:15,  4.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 253/1175 [00:40<03:14,  4.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 255/1175 [00:41<03:12,  4.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 256/1175 [00:41<03:15,  4.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 258/1175 [00:41<03:05,  4.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 260/1175 [00:41<02:50,  5.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 262/1175 [00:42<02:41,  5.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 263/1175 [00:42<02:50,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 265/1175 [00:42<03:01,  5.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 268/1175 [00:43<02:50,  5.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 270/1175 [00:43<02:51,  5.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 271/1175 [00:44<03:10,  4.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 273/1175 [00:44<03:07,  4.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 275/1175 [00:44<02:59,  5.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▎       | 277/1175 [00:45<02:55,  5.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▎       | 279/1175 [00:45<02:30,  5.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 281/1175 [00:45<02:20,  6.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 283/1175 [00:46<02:20,  6.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 285/1175 [00:46<02:11,  6.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 287/1175 [00:46<02:08,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 289/1175 [00:47<02:06,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 291/1175 [00:47<02:06,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 293/1175 [00:47<02:09,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 295/1175 [00:48<02:07,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 297/1175 [00:48<02:06,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 299/1175 [00:48<02:06,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 301/1175 [00:48<02:09,  6.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 303/1175 [00:49<02:06,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 305/1175 [00:49<02:09,  6.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 307/1175 [00:49<02:06,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▋       | 309/1175 [00:50<02:05,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▋       | 311/1175 [00:50<02:04,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 313/1175 [00:50<02:05,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 315/1175 [00:50<02:02,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 317/1175 [00:51<02:01,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 319/1175 [00:51<02:09,  6.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 321/1175 [00:51<02:04,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 323/1175 [00:52<02:04,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 325/1175 [00:52<02:00,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 327/1175 [00:52<02:07,  6.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 329/1175 [00:52<01:59,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 331/1175 [00:53<01:57,  7.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 333/1175 [00:53<02:01,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▊       | 335/1175 [00:53<01:58,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▊       | 337/1175 [00:54<01:58,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 339/1175 [00:54<01:58,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 341/1175 [00:54<02:01,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 343/1175 [00:55<01:59,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 345/1175 [00:55<01:57,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 346/1175 [00:55<02:09,  6.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 347/1175 [00:55<02:29,  5.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 348/1175 [00:55<02:39,  5.18it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 349/1175 [00:56<02:51,  4.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 350/1175 [00:56<02:54,  4.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 352/1175 [00:56<02:50,  4.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 355/1175 [00:57<02:43,  5.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 356/1175 [00:57<02:50,  4.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 358/1175 [00:58<02:44,  4.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 360/1175 [00:58<02:24,  5.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 361/1175 [00:58<02:23,  5.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 364/1175 [00:59<02:35,  5.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 365/1175 [00:59<02:44,  4.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 366/1175 [00:59<02:47,  4.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 367/1175 [00:59<03:00,  4.47it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███▏      | 370/1175 [01:00<02:46,  4.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 372/1175 [01:00<02:42,  4.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 374/1175 [01:01<02:19,  5.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 376/1175 [01:01<02:05,  6.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 378/1175 [01:01<01:59,  6.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 380/1175 [01:02<01:57,  6.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 382/1175 [01:02<01:58,  6.70it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 384/1175 [01:02<01:54,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 386/1175 [01:02<01:54,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 388/1175 [01:03<02:00,  6.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 390/1175 [01:03<01:55,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 392/1175 [01:03<01:53,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▎      | 394/1175 [01:04<01:50,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▎      | 396/1175 [01:04<01:53,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 398/1175 [01:04<01:54,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 400/1175 [01:04<01:53,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 402/1175 [01:05<01:55,  6.70it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 404/1175 [01:05<01:50,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 406/1175 [01:05<01:50,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 408/1175 [01:06<01:47,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 410/1175 [01:06<01:49,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 412/1175 [01:06<01:48,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 414/1175 [01:07<01:51,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 416/1175 [01:07<01:47,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 418/1175 [01:07<01:51,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 420/1175 [01:07<01:47,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 422/1175 [01:08<01:46,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 424/1175 [01:08<01:51,  6.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▋      | 426/1175 [01:08<01:47,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▋      | 428/1175 [01:09<01:45,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 430/1175 [01:09<01:45,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 432/1175 [01:09<01:49,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 434/1175 [01:09<01:47,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 436/1175 [01:10<01:43,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 438/1175 [01:10<01:42,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 440/1175 [01:10<01:51,  6.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 442/1175 [01:11<02:00,  6.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 443/1175 [01:11<02:10,  5.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 446/1175 [01:11<02:19,  5.24it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 447/1175 [01:12<02:21,  5.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 449/1175 [01:12<02:35,  4.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 451/1175 [01:13<02:34,  4.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▊      | 454/1175 [01:13<02:18,  5.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▊      | 455/1175 [01:13<02:21,  5.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 456/1175 [01:14<02:23,  5.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 457/1175 [01:14<02:35,  4.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 458/1175 [01:14<02:37,  4.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 459/1175 [01:14<02:42,  4.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 460/1175 [01:14<02:46,  4.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 461/1175 [01:15<02:46,  4.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 462/1175 [01:15<02:46,  4.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 464/1175 [01:15<02:36,  4.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|███▉      | 465/1175 [01:16<02:33,  4.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|███▉      | 467/1175 [01:16<02:20,  5.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|███▉      | 469/1175 [01:16<02:02,  5.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 471/1175 [01:17<01:55,  6.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 473/1175 [01:17<01:45,  6.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 475/1175 [01:17<01:45,  6.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 477/1175 [01:17<01:42,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 479/1175 [01:18<01:44,  6.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 481/1175 [01:18<01:40,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 483/1175 [01:18<01:46,  6.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████▏     | 485/1175 [01:19<01:43,  6.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████▏     | 487/1175 [01:19<01:39,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 489/1175 [01:19<01:40,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 491/1175 [01:20<01:38,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 493/1175 [01:20<01:41,  6.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 495/1175 [01:20<01:36,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 497/1175 [01:20<01:34,  7.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 499/1175 [01:21<01:32,  7.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 501/1175 [01:21<01:37,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 503/1175 [01:21<01:36,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 505/1175 [01:22<01:34,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 507/1175 [01:22<01:37,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 509/1175 [01:22<01:39,  6.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 511/1175 [01:22<01:35,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▎     | 513/1175 [01:23<01:34,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 515/1175 [01:23<01:33,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 517/1175 [01:23<01:36,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 519/1175 [01:24<01:32,  7.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 521/1175 [01:24<01:29,  7.32it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 523/1175 [01:24<01:33,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 525/1175 [01:24<01:29,  7.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 527/1175 [01:25<01:33,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 529/1175 [01:25<01:35,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 531/1175 [01:25<01:33,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 533/1175 [01:26<01:31,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 535/1175 [01:26<01:44,  6.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 536/1175 [01:26<01:56,  5.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 537/1175 [01:26<02:03,  5.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 538/1175 [01:27<02:09,  4.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 541/1175 [01:27<02:09,  4.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 542/1175 [01:27<02:06,  5.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 543/1175 [01:28<02:09,  4.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▋     | 544/1175 [01:28<02:07,  4.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 547/1175 [01:28<02:01,  5.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 549/1175 [01:29<01:55,  5.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 550/1175 [01:29<01:54,  5.45it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 552/1175 [01:29<02:12,  4.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 554/1175 [01:30<02:10,  4.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 555/1175 [01:30<02:13,  4.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 556/1175 [01:30<02:15,  4.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 557/1175 [01:31<02:18,  4.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 558/1175 [01:31<02:15,  4.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 560/1175 [01:31<02:04,  4.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 562/1175 [01:31<01:43,  5.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 564/1175 [01:32<01:35,  6.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 566/1175 [01:32<01:30,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 568/1175 [01:32<01:27,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▊     | 570/1175 [01:33<01:27,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▊     | 572/1175 [01:33<01:24,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 574/1175 [01:33<01:25,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 576/1175 [01:33<01:25,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 578/1175 [01:34<01:28,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 580/1175 [01:34<01:25,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 582/1175 [01:34<01:22,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 584/1175 [01:35<01:23,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 586/1175 [01:35<01:26,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 588/1175 [01:35<01:23,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 590/1175 [01:35<01:22,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 592/1175 [01:36<01:24,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 594/1175 [01:36<01:27,  6.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 596/1175 [01:36<01:24,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 598/1175 [01:37<01:21,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 600/1175 [01:37<01:23,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 602/1175 [01:37<01:23,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████▏    | 604/1175 [01:38<01:25,  6.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 606/1175 [01:38<01:23,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 608/1175 [01:38<01:21,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 610/1175 [01:38<01:18,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 612/1175 [01:39<01:19,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 614/1175 [01:39<01:20,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 616/1175 [01:39<01:19,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 618/1175 [01:40<01:21,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 620/1175 [01:40<01:20,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 622/1175 [01:40<01:18,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 624/1175 [01:40<01:18,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 626/1175 [01:41<01:17,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 627/1175 [01:41<01:18,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▎    | 629/1175 [01:41<01:38,  5.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▎    | 631/1175 [01:42<01:40,  5.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 632/1175 [01:42<01:45,  5.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 633/1175 [01:42<01:47,  5.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 634/1175 [01:42<01:50,  4.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 635/1175 [01:43<01:54,  4.70it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 636/1175 [01:43<01:56,  4.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 637/1175 [01:43<01:54,  4.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 638/1175 [01:43<01:55,  4.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 640/1175 [01:44<01:52,  4.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 643/1175 [01:44<01:44,  5.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 644/1175 [01:44<01:39,  5.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 645/1175 [01:45<01:48,  4.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 646/1175 [01:45<01:49,  4.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 647/1175 [01:45<01:50,  4.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 648/1175 [01:45<01:54,  4.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 649/1175 [01:45<01:56,  4.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 650/1175 [01:46<01:53,  4.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 651/1175 [01:46<01:54,  4.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 652/1175 [01:46<01:53,  4.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 654/1175 [01:47<01:51,  4.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 656/1175 [01:47<01:28,  5.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 658/1175 [01:47<01:22,  6.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 660/1175 [01:47<01:18,  6.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▋    | 662/1175 [01:48<01:18,  6.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 664/1175 [01:48<01:13,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 666/1175 [01:48<01:13,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 668/1175 [01:49<01:16,  6.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 670/1175 [01:49<01:16,  6.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 672/1175 [01:49<01:14,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 674/1175 [01:50<01:18,  6.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 676/1175 [01:50<01:15,  6.65it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 678/1175 [01:50<01:14,  6.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 680/1175 [01:50<01:13,  6.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 682/1175 [01:51<01:13,  6.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 684/1175 [01:51<01:11,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 686/1175 [01:51<01:10,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▊    | 688/1175 [01:52<01:13,  6.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▊    | 690/1175 [01:52<01:12,  6.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 692/1175 [01:52<01:10,  6.85it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 694/1175 [01:53<01:11,  6.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 696/1175 [01:53<01:13,  6.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 698/1175 [01:53<01:11,  6.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 700/1175 [01:53<01:09,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 702/1175 [01:54<01:09,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|█████▉    | 704/1175 [01:54<01:09,  6.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 706/1175 [01:54<01:08,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 708/1175 [01:55<01:07,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 710/1175 [01:55<01:06,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 712/1175 [01:55<01:05,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 714/1175 [01:55<01:06,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 716/1175 [01:56<01:06,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 718/1175 [01:56<01:06,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████▏   | 720/1175 [01:56<01:04,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████▏   | 721/1175 [01:57<01:11,  6.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 723/1175 [01:57<01:22,  5.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 724/1175 [01:57<01:25,  5.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 725/1175 [01:57<01:29,  5.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 727/1175 [01:58<01:29,  5.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 729/1175 [01:58<01:28,  5.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 730/1175 [01:58<01:30,  4.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 731/1175 [01:59<01:32,  4.82it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 732/1175 [01:59<01:36,  4.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 733/1175 [01:59<01:37,  4.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 734/1175 [01:59<01:38,  4.49it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 735/1175 [02:00<01:39,  4.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 736/1175 [02:00<01:37,  4.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 737/1175 [02:00<01:38,  4.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 738/1175 [02:00<01:41,  4.31it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 739/1175 [02:00<01:42,  4.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 741/1175 [02:01<01:32,  4.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 743/1175 [02:01<01:27,  4.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 744/1175 [02:01<01:28,  4.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 745/1175 [02:02<01:29,  4.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▎   | 748/1175 [02:02<01:22,  5.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 750/1175 [02:03<01:15,  5.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 752/1175 [02:03<01:07,  6.26it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 754/1175 [02:03<01:03,  6.67it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 756/1175 [02:03<01:02,  6.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 758/1175 [02:04<01:03,  6.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 760/1175 [02:04<01:01,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 762/1175 [02:04<01:00,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 764/1175 [02:05<01:04,  6.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 766/1175 [02:05<01:00,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 768/1175 [02:05<00:58,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 770/1175 [02:06<00:57,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 772/1175 [02:06<00:58,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 774/1175 [02:06<00:57,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 776/1175 [02:06<00:57,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 778/1175 [02:07<00:56,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▋   | 780/1175 [02:07<00:55,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 782/1175 [02:07<00:56,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 784/1175 [02:08<00:57,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 786/1175 [02:08<00:56,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 788/1175 [02:08<00:56,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 790/1175 [02:08<00:56,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 792/1175 [02:09<00:56,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 794/1175 [02:09<00:55,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 796/1175 [02:09<00:56,  6.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 798/1175 [02:10<00:57,  6.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 800/1175 [02:10<00:58,  6.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 802/1175 [02:10<00:54,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 804/1175 [02:11<00:53,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▊   | 806/1175 [02:11<00:54,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 808/1175 [02:11<00:55,  6.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 810/1175 [02:11<00:54,  6.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 812/1175 [02:12<00:52,  6.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 814/1175 [02:12<00:57,  6.27it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 815/1175 [02:12<01:05,  5.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 817/1175 [02:13<01:09,  5.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 818/1175 [02:13<01:12,  4.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 820/1175 [02:13<01:11,  4.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 823/1175 [02:14<01:03,  5.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 825/1175 [02:14<01:03,  5.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 827/1175 [02:15<01:02,  5.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 828/1175 [02:15<01:03,  5.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 831/1175 [02:15<01:03,  5.40it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 833/1175 [02:16<01:05,  5.21it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 835/1175 [02:16<01:00,  5.60it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 837/1175 [02:16<00:57,  5.86it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████▏  | 839/1175 [02:17<00:59,  5.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████▏  | 840/1175 [02:17<00:59,  5.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 841/1175 [02:17<01:03,  5.29it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 842/1175 [02:17<01:05,  5.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 843/1175 [02:18<01:10,  4.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 846/1175 [02:18<01:04,  5.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 848/1175 [02:19<00:54,  6.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 850/1175 [02:19<00:51,  6.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 852/1175 [02:19<00:47,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 854/1175 [02:19<00:47,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 856/1175 [02:20<00:47,  6.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 858/1175 [02:20<00:46,  6.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 860/1175 [02:20<00:44,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 862/1175 [02:21<00:44,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▎  | 864/1175 [02:21<00:43,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▎  | 866/1175 [02:21<00:45,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 868/1175 [02:21<00:43,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 870/1175 [02:22<00:43,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 872/1175 [02:22<00:43,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 874/1175 [02:22<00:44,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 876/1175 [02:23<00:43,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 878/1175 [02:23<00:43,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 880/1175 [02:23<00:42,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 882/1175 [02:23<00:41,  7.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 884/1175 [02:24<00:41,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 886/1175 [02:24<00:40,  7.14it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 888/1175 [02:24<00:41,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 890/1175 [02:25<00:41,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 892/1175 [02:25<00:41,  6.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 894/1175 [02:25<00:40,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▋  | 896/1175 [02:25<00:39,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▋  | 898/1175 [02:26<00:38,  7.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 900/1175 [02:26<00:40,  6.77it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 902/1175 [02:26<00:39,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 904/1175 [02:27<00:38,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 906/1175 [02:27<00:38,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 908/1175 [02:27<00:38,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 910/1175 [02:28<00:39,  6.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 912/1175 [02:28<00:37,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 914/1175 [02:28<00:37,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 915/1175 [02:28<00:42,  6.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 918/1175 [02:29<00:47,  5.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 919/1175 [02:29<00:49,  5.13it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 921/1175 [02:30<00:49,  5.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▊  | 923/1175 [02:30<00:46,  5.42it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▊  | 925/1175 [02:30<00:45,  5.46it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 926/1175 [02:31<00:49,  4.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 929/1175 [02:31<00:46,  5.25it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 930/1175 [02:31<00:51,  4.75it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 933/1175 [02:32<00:50,  4.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 934/1175 [02:32<00:53,  4.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 936/1175 [02:33<00:53,  4.50it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 937/1175 [02:33<00:52,  4.53it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|███████▉  | 939/1175 [02:33<00:48,  4.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 941/1175 [02:34<00:46,  5.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 943/1175 [02:34<00:40,  5.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 945/1175 [02:34<00:36,  6.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 947/1175 [02:35<00:33,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 949/1175 [02:35<00:32,  6.93it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 951/1175 [02:35<00:33,  6.66it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 953/1175 [02:35<00:30,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████▏ | 955/1175 [02:36<00:31,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████▏ | 957/1175 [02:36<00:30,  7.06it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 959/1175 [02:36<00:30,  7.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 961/1175 [02:37<00:30,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 963/1175 [02:37<00:31,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 965/1175 [02:37<00:29,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 967/1175 [02:37<00:28,  7.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 969/1175 [02:38<00:29,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 971/1175 [02:38<00:28,  7.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 973/1175 [02:38<00:29,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 975/1175 [02:39<00:28,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 977/1175 [02:39<00:29,  6.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 979/1175 [02:39<00:28,  6.91it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 981/1175 [02:39<00:27,  7.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▎ | 983/1175 [02:40<00:27,  7.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 985/1175 [02:40<00:28,  6.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 987/1175 [02:40<00:27,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 989/1175 [02:41<00:26,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 991/1175 [02:41<00:27,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 993/1175 [02:41<00:25,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 995/1175 [02:41<00:25,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 997/1175 [02:42<00:25,  7.05it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 999/1175 [02:42<00:25,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1001/1175 [02:42<00:24,  7.10it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 1003/1175 [02:43<00:24,  7.15it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1005/1175 [02:43<00:23,  7.19it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1007/1175 [02:43<00:24,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1009/1175 [02:44<00:23,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1010/1175 [02:44<00:26,  6.33it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1011/1175 [02:44<00:28,  5.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 1013/1175 [02:44<00:30,  5.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▋ | 1015/1175 [02:45<00:28,  5.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1017/1175 [02:45<00:28,  5.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1018/1175 [02:45<00:29,  5.30it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1019/1175 [02:46<00:33,  4.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1020/1175 [02:46<00:33,  4.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1021/1175 [02:46<00:33,  4.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1024/1175 [02:47<00:31,  4.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1025/1175 [02:47<00:31,  4.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1026/1175 [02:47<00:31,  4.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 1027/1175 [02:47<00:32,  4.55it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1029/1175 [02:48<00:30,  4.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1030/1175 [02:48<00:30,  4.70it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1031/1175 [02:48<00:32,  4.44it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1032/1175 [02:48<00:31,  4.52it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1033/1175 [02:49<00:32,  4.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1034/1175 [02:49<00:32,  4.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1035/1175 [02:49<00:32,  4.35it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1037/1175 [02:49<00:29,  4.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 1039/1175 [02:50<00:24,  5.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▊ | 1041/1175 [02:50<00:21,  6.11it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1043/1175 [02:50<00:20,  6.54it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1045/1175 [02:51<00:19,  6.59it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1047/1175 [02:51<00:18,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1049/1175 [02:51<00:17,  7.03it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 1051/1175 [02:51<00:17,  6.98it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1053/1175 [02:52<00:17,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1055/1175 [02:52<00:17,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 1057/1175 [02:52<00:17,  6.94it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1059/1175 [02:53<00:16,  7.07it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1061/1175 [02:53<00:17,  6.57it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 1063/1175 [02:53<00:16,  6.79it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1065/1175 [02:54<00:15,  7.00it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1067/1175 [02:54<00:16,  6.68it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1069/1175 [02:54<00:15,  6.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 1071/1175 [02:54<00:15,  6.78it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████▏| 1073/1175 [02:55<00:14,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████▏| 1075/1175 [02:55<00:14,  6.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1077/1175 [02:55<00:14,  6.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1079/1175 [02:56<00:14,  6.74it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1081/1175 [02:56<00:13,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1083/1175 [02:56<00:13,  7.04it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 1085/1175 [02:57<00:13,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1087/1175 [02:57<00:13,  6.58it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1089/1175 [02:57<00:12,  6.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1091/1175 [02:57<00:12,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1093/1175 [02:58<00:11,  6.96it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1095/1175 [02:58<00:12,  6.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 1097/1175 [02:58<00:11,  6.73it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▎| 1099/1175 [02:59<00:11,  6.81it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▎| 1101/1175 [02:59<00:10,  6.97it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1103/1175 [02:59<00:10,  6.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1104/1175 [02:59<00:11,  6.08it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1106/1175 [03:00<00:12,  5.41it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 1109/1175 [03:00<00:12,  5.39it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1111/1175 [03:01<00:11,  5.61it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1113/1175 [03:01<00:11,  5.20it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 1115/1175 [03:02<00:11,  5.28it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1117/1175 [03:02<00:11,  5.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1118/1175 [03:02<00:11,  4.92it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1119/1175 [03:02<00:12,  4.63it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 1121/1175 [03:03<00:11,  4.51it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1123/1175 [03:03<00:11,  4.62it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1124/1175 [03:03<00:11,  4.58it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1125/1175 [03:04<00:11,  4.43it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1126/1175 [03:04<00:11,  4.34it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1127/1175 [03:04<00:11,  4.36it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1128/1175 [03:04<00:10,  4.37it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 1129/1175 [03:05<00:10,  4.23it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▋| 1131/1175 [03:05<00:08,  4.99it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▋| 1133/1175 [03:05<00:07,  5.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1135/1175 [03:06<00:06,  6.48it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1137/1175 [03:06<00:05,  6.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1139/1175 [03:06<00:05,  6.64it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1141/1175 [03:06<00:04,  6.83it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1143/1175 [03:07<00:04,  6.69it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 1145/1175 [03:07<00:04,  6.71it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1147/1175 [03:07<00:04,  6.72it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1149/1175 [03:08<00:03,  6.90it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1151/1175 [03:08<00:03,  6.76it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1153/1175 [03:08<00:03,  6.87it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1155/1175 [03:09<00:02,  6.95it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 1157/1175 [03:09<00:02,  6.89it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▊| 1159/1175 [03:09<00:02,  7.02it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1161/1175 [03:09<00:01,  7.16it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1163/1175 [03:10<00:01,  6.80it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1165/1175 [03:10<00:01,  6.88it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1167/1175 [03:10<00:01,  7.01it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 1169/1175 [03:11<00:00,  7.09it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1171/1175 [03:11<00:00,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|█████████▉| 1173/1175 [03:11<00:00,  6.84it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|██████████| 1175/1175 [03:11<00:00,  6.12it/s]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
TEXT: torch.Size([3, 384])
IMAGE: torch.Size([3, 384])
GRAPH: torch.Size([3, 384])
Epoch 5 Loss: 0.4034218884909407

In [ ]:
# ============================================================
# EVALUATION
# ============================================================

model.eval()

all_preds=[]

all_labels=[]

with torch.no_grad():

    for batch in tqdm(dev_loader):

        labels=batch["labels"].to(
            CFG.DEVICE
        )

        with torch.amp.autocast("cuda"):

            logits=model(batch)

        probs=torch.sigmoid(logits)

        preds=(probs>0.5).long()

        all_preds.extend(
            preds.cpu().numpy()
        )

        all_labels.extend(
            labels.cpu().numpy()
        )

acc=accuracy_score(
    all_labels,
    all_preds
)

f1=f1_score(
    all_labels,
    all_preds
)

print("Accuracy:",acc)

print("F1:",f1)

# ============================================================
# SAVE
# ============================================================

torch.save(
    model.state_dict(),
    "lightweight_multimodal_model.pt"
)

print("Model Saved")

  1%|▏         | 1/75 [00:03<04:40,  3.79s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 2/75 [00:07<04:18,  3.54s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 3/75 [00:10<04:07,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▌         | 4/75 [00:13<03:58,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 5/75 [00:17<03:58,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 6/75 [00:20<03:54,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 7/75 [00:24<03:57,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 8/75 [00:27<03:55,  3.51s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 9/75 [00:31<03:54,  3.55s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 10/75 [00:35<04:00,  3.71s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▍        | 11/75 [00:39<03:55,  3.69s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 12/75 [00:42<03:47,  3.61s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 13/75 [00:45<03:40,  3.55s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▊        | 14/75 [00:49<03:36,  3.54s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 15/75 [00:53<03:36,  3.61s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██▏       | 16/75 [00:56<03:30,  3.56s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 17/75 [01:00<03:21,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 18/75 [01:03<03:15,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▌       | 19/75 [01:07<03:19,  3.57s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 20/75 [01:10<03:11,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 21/75 [01:13<03:02,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 22/75 [01:17<03:00,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 23/75 [01:20<02:59,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 24/75 [01:24<02:54,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 25/75 [01:27<02:51,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▍      | 26/75 [01:30<02:45,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 27/75 [01:34<02:43,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 28/75 [01:37<02:38,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▊      | 29/75 [01:40<02:31,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 30/75 [01:43<02:27,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████▏     | 31/75 [01:48<02:36,  3.55s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 32/75 [01:51<02:32,  3.54s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 33/75 [01:54<02:27,  3.50s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▌     | 34/75 [01:58<02:19,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 35/75 [02:01<02:19,  3.50s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 36/75 [02:05<02:21,  3.62s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 37/75 [02:09<02:15,  3.56s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 38/75 [02:12<02:07,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 39/75 [02:15<02:03,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 40/75 [02:19<01:59,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▍    | 41/75 [02:22<01:59,  3.52s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 42/75 [02:26<01:52,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 43/75 [02:29<01:47,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▊    | 44/75 [02:32<01:43,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 45/75 [02:36<01:44,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████▏   | 46/75 [02:39<01:36,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 47/75 [02:42<01:35,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 48/75 [02:46<01:30,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▌   | 49/75 [02:49<01:25,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 50/75 [02:52<01:21,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 51/75 [02:55<01:18,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 52/75 [02:59<01:14,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 53/75 [03:02<01:10,  3.19s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 54/75 [03:05<01:07,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 55/75 [03:08<01:05,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▍  | 56/75 [03:11<01:01,  3.21s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 57/75 [03:15<00:57,  3.22s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 58/75 [03:18<00:55,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▊  | 59/75 [03:21<00:52,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 60/75 [03:25<00:49,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████▏ | 61/75 [03:30<00:53,  3.82s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 62/75 [03:33<00:47,  3.66s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 63/75 [03:36<00:42,  3.51s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▌ | 64/75 [03:39<00:38,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 65/75 [03:43<00:34,  3.45s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 66/75 [03:46<00:30,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 67/75 [03:50<00:27,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 68/75 [03:53<00:23,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 69/75 [03:56<00:19,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 70/75 [03:59<00:16,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▍| 71/75 [04:03<00:13,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 72/75 [04:06<00:09,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 73/75 [04:09<00:06,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▊| 74/75 [04:12<00:03,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|██████████| 75/75 [04:16<00:00,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
Accuracy: 0.785
F1: 0.5930599369085173
Model Saved

In [ ]:
TEST_TEXT_CSV = "/content/test.csv"
TEST_IMG_DIR  = "/content/drive/MyDrive/test_eng"

In [ ]:
txt_df = pd.read_csv(TEST_TEXT_CSV)

# expected columns: image_id, transcriptions
txt_df = txt_df[["image_id", "transcriptions"]].copy()
txt_df.columns = ["image_id", "transcription"]

txt_df["image_id"] = pd.to_numeric(txt_df["image_id"], errors="coerce")
txt_df = txt_df.dropna(subset=["image_id"]).reset_index(drop=True)
txt_df["image_id"] = txt_df["image_id"].astype(int)

In [ ]:
rows = []
valid_ext = (".jpg", ".jpeg", ".png", ".webp", ".bmp", ".jfif")

for root, dirs, files in os.walk(TEST_IMG_DIR):
    for fname in files:
        if fname.lower().endswith(valid_ext):
            path = os.path.join(root, fname)
            stem = os.path.splitext(fname)[0]

            digits = re.sub(r"\D", "", stem)
            if digits == "":
                continue

            img_id = int(digits)

            rows.append({
                "image_id": img_id,
                "image_path": path
            })

img_df = pd.DataFrame(rows)
img_df = img_df.drop_duplicates(subset="image_id", keep="first")

In [ ]:
FUSED_TEST_CSV = "fused_test.csv"

In [ ]:
test_df = txt_df.merge(img_df, on="image_id", how="inner")
test_df = test_df[["image_id", "image_path", "transcription"]]

print("Matched rows:", len(test_df))
print(test_df.head())

test_df.to_csv(FUSED_TEST_CSV, index=False)
print("Saved fused test:", FUSED_TEST_CSV)

Matched rows: 1000
   image_id                                 image_path  \
0     15236  /content/drive/MyDrive/test_eng/15236.jpg
1     15805  /content/drive/MyDrive/test_eng/15805.jpg
2     16254  /content/drive/MyDrive/test_eng/16254.jpg
3     16191  /content/drive/MyDrive/test_eng/16191.jpg
4     15952  /content/drive/MyDrive/test_eng/15952.jpg

                                       transcription
0  FACEBOOK SINGLES GROUPS BELIKE WHEN A NEW WOMA...
1    SO, IF YOU'RE A FEMINIST HOW CAN YOU EAT DAIRY?
2         WHEN A CUTE GIRL LEFT YOUR MESSAGE ON SEEN
3  Photographing something you want to show every...
4  HEY BABE CAN YOU MAKE ME A SANDWICH? Hey babe ...
Saved fused test: fused_test.csv

In [ ]:
ddd=pd.read_csv('/content/test.csv')

In [ ]:
ddd.head()

,image_id,image_path,transcription
0,15236,/content/drive/MyDrive/test_eng/15236.jpg,FACEBOOK SINGLES GROUPS BELIKE WHEN A NEW WOMA...
1,15805,/content/drive/MyDrive/test_eng/15805.jpg,"SO, IF YOU'RE A FEMINIST HOW CAN YOU EAT DAIRY?"
2,16254,/content/drive/MyDrive/test_eng/16254.jpg,WHEN A CUTE GIRL LEFT YOUR MESSAGE ON SEEN
3,16191,/content/drive/MyDrive/test_eng/16191.jpg,Photographing something you want to show every...
4,15952,/content/drive/MyDrive/test_eng/15952.jpg,HEY BABE CAN YOU MAKE ME A SANDWICH? Hey babe ...

In [ ]:
ddd.shape()

TypeError: 'tuple' object is not callable

In [ ]:
# ============================================================
# TEST DATASET
# ============================================================

class TestDataset(Dataset):

    def __init__(self,csv_path,graphs):

        self.df=pd.read_csv(csv_path)

        self.graphs=graphs

    def __len__(self):

        return len(self.df)

    def __getitem__(self,idx):

        row=self.df.iloc[idx]

        image=Image.open(
            row["image_path"]
        ).convert("RGB")

        text=str(
            row["transcription"]
        )

        graph=self.graphs[idx]

        return {
            "image":image,
            "text":text,
            "graph":graph
        }

# ============================================================
# TEST COLLATE
# ============================================================

def test_collate_fn(batch):

    images=[
        x["image"] for x in batch
    ]

    texts=[
        x["text"] for x in batch
    ]

    graphs=Batch.from_data_list(
        [x["graph"] for x in batch]
    )

    return {
        "images":images,
        "texts":texts,
        "graphs":graphs
    }

# ============================================================
# TEST GRAPH CACHE
# ============================================================

TEST_CSV="/content/test.csv"

TEST_GRAPH_CACHE="/content/test_graphs.pt"

if not os.path.exists(TEST_GRAPH_CACHE):

    test_graphs=build_graph_cache(
        TEST_CSV
    )

    torch.save(
        test_graphs,
        TEST_GRAPH_CACHE
    )

test_graphs=torch.load(
    TEST_GRAPH_CACHE,
    weights_only=False
)

# ============================================================
# TEST LOADER
# ============================================================

test_dataset=TestDataset(
    TEST_CSV,
    test_graphs
)

test_loader=DataLoader(
    test_dataset,
    batch_size=CFG.BATCH_SIZE,
    shuffle=False,
    collate_fn=test_collate_fn,
    pin_memory=True
)

# ============================================================
# TEST PREDICTION
# ============================================================

model.eval()

all_probs=[]

all_preds=[]

with torch.no_grad():

    for batch in tqdm(test_loader):

        with torch.amp.autocast("cuda"):

            logits=model(batch)

        probs=torch.sigmoid(logits)

        preds=(probs>0.5).long()

        all_probs.extend(
            probs.cpu().numpy()
        )

        all_preds.extend(
            preds.cpu().numpy()
        )

# ============================================================
# SAVE PREDICTIONS
# ============================================================

test_df=pd.read_csv(TEST_CSV)

test_df["prediction"]=all_preds

test_df["probability"]=all_probs

test_df.to_csv(
    "test_predictions.csv",
    index=False
)

print(test_df.head())

print("Test Predictions Saved")

100%|██████████| 1000/1000 [00:17<00:00, 58.13it/s]
  1%|          | 1/125 [00:04<08:23,  4.06s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 2/125 [00:07<07:32,  3.67s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  2%|▏         | 3/125 [00:11<07:26,  3.66s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  3%|▎         | 4/125 [00:14<07:15,  3.60s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  4%|▍         | 5/125 [00:18<07:20,  3.67s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  5%|▍         | 6/125 [00:21<07:05,  3.57s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▌         | 7/125 [00:25<06:53,  3.50s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  6%|▋         | 8/125 [00:28<07:02,  3.61s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  7%|▋         | 9/125 [00:32<07:04,  3.66s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  8%|▊         | 10/125 [00:37<07:38,  3.99s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

  9%|▉         | 11/125 [00:41<07:27,  3.92s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|▉         | 12/125 [00:44<07:11,  3.82s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 10%|█         | 13/125 [00:48<07:08,  3.83s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 11%|█         | 14/125 [00:52<06:57,  3.76s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 12%|█▏        | 15/125 [00:55<06:44,  3.68s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 13%|█▎        | 16/125 [00:59<06:36,  3.64s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▎        | 17/125 [01:02<06:26,  3.58s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 14%|█▍        | 18/125 [01:06<06:26,  3.61s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 15%|█▌        | 19/125 [01:09<06:20,  3.59s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 16%|█▌        | 20/125 [01:13<06:06,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 17%|█▋        | 21/125 [01:16<06:01,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 22/125 [01:20<06:05,  3.55s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 18%|█▊        | 23/125 [01:23<05:55,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 19%|█▉        | 24/125 [01:27<05:52,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 20%|██        | 25/125 [01:30<05:48,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 21%|██        | 26/125 [01:34<05:52,  3.56s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 27/125 [01:37<05:41,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 22%|██▏       | 28/125 [01:41<05:36,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 23%|██▎       | 29/125 [01:44<05:34,  3.48s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 24%|██▍       | 30/125 [01:48<05:31,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 25%|██▍       | 31/125 [01:51<05:16,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▌       | 32/125 [01:54<05:14,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 26%|██▋       | 33/125 [01:58<05:10,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 27%|██▋       | 34/125 [02:01<05:15,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 28%|██▊       | 35/125 [02:04<05:05,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 29%|██▉       | 36/125 [02:08<05:01,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|██▉       | 37/125 [02:11<04:56,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 30%|███       | 38/125 [02:14<04:51,  3.36s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 31%|███       | 39/125 [02:18<04:48,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 32%|███▏      | 40/125 [02:21<04:41,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 33%|███▎      | 41/125 [02:25<04:59,  3.57s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▎      | 42/125 [02:29<05:00,  3.62s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 34%|███▍      | 43/125 [02:33<05:11,  3.80s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 35%|███▌      | 44/125 [02:37<04:56,  3.66s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 36%|███▌      | 45/125 [02:40<04:40,  3.50s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 37%|███▋      | 46/125 [02:43<04:34,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 47/125 [02:48<05:01,  3.87s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 38%|███▊      | 48/125 [02:51<04:48,  3.75s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 39%|███▉      | 49/125 [02:55<04:38,  3.67s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 40%|████      | 50/125 [02:58<04:35,  3.67s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 41%|████      | 51/125 [03:02<04:25,  3.59s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 52/125 [03:05<04:13,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 42%|████▏     | 53/125 [03:09<04:11,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 43%|████▎     | 54/125 [03:12<04:04,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 44%|████▍     | 55/125 [03:15<03:58,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 45%|████▍     | 56/125 [03:19<03:53,  3.38s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▌     | 57/125 [03:22<03:50,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 46%|████▋     | 58/125 [03:25<03:45,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 47%|████▋     | 59/125 [03:29<03:40,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 48%|████▊     | 60/125 [03:32<03:42,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 49%|████▉     | 61/125 [03:36<03:40,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|████▉     | 62/125 [03:39<03:41,  3.51s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 50%|█████     | 63/125 [03:43<03:44,  3.62s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 51%|█████     | 64/125 [03:47<03:35,  3.53s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 52%|█████▏    | 65/125 [03:50<03:30,  3.51s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 53%|█████▎    | 66/125 [03:53<03:24,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▎    | 67/125 [03:57<03:16,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 54%|█████▍    | 68/125 [04:00<03:12,  3.37s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 55%|█████▌    | 69/125 [04:03<03:07,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 56%|█████▌    | 70/125 [04:06<03:02,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 57%|█████▋    | 71/125 [04:10<02:56,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 72/125 [04:13<02:54,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 58%|█████▊    | 73/125 [04:16<02:48,  3.24s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 59%|█████▉    | 74/125 [04:20<02:56,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 60%|██████    | 75/125 [04:23<02:50,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 61%|██████    | 76/125 [04:27<02:51,  3.50s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 77/125 [04:30<02:45,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 62%|██████▏   | 78/125 [04:34<02:41,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 63%|██████▎   | 79/125 [04:37<02:36,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 64%|██████▍   | 80/125 [04:41<02:35,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 65%|██████▍   | 81/125 [04:44<02:27,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▌   | 82/125 [04:47<02:22,  3.32s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 66%|██████▋   | 83/125 [04:50<02:20,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 67%|██████▋   | 84/125 [04:54<02:15,  3.31s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 68%|██████▊   | 85/125 [04:57<02:13,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 69%|██████▉   | 86/125 [05:00<02:10,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|██████▉   | 87/125 [05:04<02:03,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 70%|███████   | 88/125 [05:07<02:00,  3.25s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 71%|███████   | 89/125 [05:10<01:57,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 72%|███████▏  | 90/125 [05:13<01:53,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 73%|███████▎  | 91/125 [05:17<01:52,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▎  | 92/125 [05:21<01:54,  3.47s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 74%|███████▍  | 93/125 [05:24<01:50,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 75%|███████▌  | 94/125 [05:28<01:48,  3.50s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 76%|███████▌  | 95/125 [05:31<01:42,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 77%|███████▋  | 96/125 [05:34<01:35,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 97/125 [05:37<01:31,  3.26s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 78%|███████▊  | 98/125 [05:40<01:29,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 79%|███████▉  | 99/125 [05:44<01:26,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 80%|████████  | 100/125 [05:47<01:22,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 81%|████████  | 101/125 [05:50<01:18,  3.27s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 102/125 [05:54<01:16,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 82%|████████▏ | 103/125 [05:57<01:13,  3.34s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 83%|████████▎ | 104/125 [06:00<01:09,  3.33s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 84%|████████▍ | 105/125 [06:04<01:05,  3.28s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 85%|████████▍ | 106/125 [06:07<01:00,  3.20s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▌ | 107/125 [06:10<00:59,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 86%|████████▋ | 108/125 [06:13<00:56,  3.30s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 87%|████████▋ | 109/125 [06:17<00:52,  3.29s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 88%|████████▊ | 110/125 [06:20<00:51,  3.44s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 89%|████████▉ | 111/125 [06:24<00:47,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|████████▉ | 112/125 [06:28<00:46,  3.56s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 90%|█████████ | 113/125 [06:31<00:41,  3.43s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 91%|█████████ | 114/125 [06:34<00:37,  3.42s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 92%|█████████▏| 115/125 [06:38<00:34,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 93%|█████████▎| 116/125 [06:41<00:31,  3.49s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▎| 117/125 [06:44<00:27,  3.39s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 94%|█████████▍| 118/125 [06:48<00:23,  3.40s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 95%|█████████▌| 119/125 [06:51<00:20,  3.35s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 96%|█████████▌| 120/125 [06:55<00:17,  3.54s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 97%|█████████▋| 121/125 [06:59<00:14,  3.52s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 122/125 [07:02<00:10,  3.51s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 98%|█████████▊| 123/125 [07:05<00:07,  3.50s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

 99%|█████████▉| 124/125 [07:09<00:03,  3.41s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])

100%|██████████| 125/125 [07:12<00:00,  3.46s/it]

TEXT: torch.Size([8, 384])
IMAGE: torch.Size([8, 384])
GRAPH: torch.Size([8, 384])
   image_id                                 image_path  \
0     15236  /content/drive/MyDrive/test_eng/15236.jpg
1     15805  /content/drive/MyDrive/test_eng/15805.jpg
2     16254  /content/drive/MyDrive/test_eng/16254.jpg
3     16191  /content/drive/MyDrive/test_eng/16191.jpg
4     15952  /content/drive/MyDrive/test_eng/15952.jpg

                                       transcription  prediction  probability
0  FACEBOOK SINGLES GROUPS BELIKE WHEN A NEW WOMA...           0     0.130371
1    SO, IF YOU'RE A FEMINIST HOW CAN YOU EAT DAIRY?           0     0.289795
2         WHEN A CUTE GIRL LEFT YOUR MESSAGE ON SEEN           0     0.170898
3  Photographing something you want to show every...           1     0.579102
4  HEY BABE CAN YOU MAKE ME A SANDWICH? Hey babe ...           0     0.424316
Test Predictions Saved

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

In [ ]:
ts=test_df

In [ ]:
test_df

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,image_id,image_path,transcription,prediction,probability
0,15236,/content/drive/MyDrive/test_eng/15236.jpg,FACEBOOK SINGLES GROUPS BELIKE WHEN A NEW WOMA...,0,0.130371
1,15805,/content/drive/MyDrive/test_eng/15805.jpg,"SO, IF YOU'RE A FEMINIST HOW CAN YOU EAT DAIRY?",0,0.289795
2,16254,/content/drive/MyDrive/test_eng/16254.jpg,WHEN A CUTE GIRL LEFT YOUR MESSAGE ON SEEN,0,0.170898
3,16191,/content/drive/MyDrive/test_eng/16191.jpg,Photographing something you want to show every...,1,0.579102
4,15952,/content/drive/MyDrive/test_eng/15952.jpg,HEY BABE CAN YOU MAKE ME A SANDWICH? Hey babe ...,0,0.424316
...,...,...,...,...,...
995,15591,/content/drive/MyDrive/test_eng/15591.jpg,IT'S NOT YOUR FAULT You didn't design the dres...,1,0.845703
996,15049,/content/drive/MyDrive/test_eng/15049.jpg,THINK ABOUT HOW MUCH BETTER HER SKIN IS BREATH...,1,0.605957
997,15363,/content/drive/MyDrive/test_eng/15363.jpg,THE STEREOTYPES ARE TRUE F SHE DOES HAVE A TIG...,1,0.722656
998,15199,/content/drive/MyDrive/test_eng/15199.jpg,DRAWS NAKED PICTURES OF BLACK WOMEN 00 0000 GE...,0,0.479736
999,15853,/content/drive/MyDrive/test_eng/15853.jpg,"""You work too much."" Me: OOL I want to be rich...",0,0.068909

In [ ]:
ts = ts.drop(columns=['image_path'], inplace=True)

In [ ]:
ts

In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score


merged = pred_df.merge(true_df, on="image_id")

y_pred = merged["prediction"]
y_true = merged["indian_labels"]

acc = accuracy_score(y_true, y_pred)
macro_f1 = f1_score(y_true, y_pred, average="macro")

print("Accuracy :", acc)
print("Macro F1 :", macro_f1)

TypeError: Labels in y_true and y_pred should be of the same type. Got y_true=['misogyny' 'not-misogyny'] and y_pred=[0 1]. Make sure that the predictions provided by the classifier coincides with the true labels.

In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score

pred_df = pd.read_csv("/content/test_predictions (3).csv")
true_df = pd.read_csv("/content/test.csv")

true_df["indian_labels"] = true_df["indian_labels"].map({
    "not-misogyny": 0,
    "misogyny": 1
})

merged = pred_df.merge(true_df, on="image_id")

y_pred = merged["prediction"]
y_true = merged["indian_labels"]

acc = accuracy_score(y_true, y_pred)
macro_f1 = f1_score(y_true, y_pred, average="macro")

print("Accuracy :", acc)
print("Macro F1 :", macro_f1)

Accuracy : 0.738
Macro F1 : 0.7170675236712972